USE gemstone_dev;

-- ── ZONES ────────────────────────────────────────────────────────────────
INSERT INTO zones (id, slug, name, region, level_min, level_max, climate, is_enabled) VALUES
  (4, 'timmorain_road', 'Timmorain Road', 'Elanith', 1, 5, 'temperate', TRUE),
  (5, 'neartofar_road', 'Neartofar Road', 'Elanith', 1, 15, 'temperate', TRUE),
  (6, 'neartofar_forest', 'Neartofar Forest', 'Elanith', 10, 20, 'temperate', TRUE),
  (7, 'toadwort', 'The Toadwort', 'Elanith', 2, 10, 'temperate', TRUE),
  (8, 'lunule_weald', 'Lunule Weald', 'Elanith', 13, 30, 'temperate', TRUE)
ON DUPLICATE KEY UPDATE name=VALUES(name);

-- ── ROOMS ────────────────────────────────────────────────────────────────
INSERT INTO rooms (id, zone_id, title, is_safe, is_supernode, is_indoor, terrain_type) VALUES
(5830, 4, 'Timmorain Road', FALSE, FALSE, FALSE, 'outdoor'),
(5831, 4, 'Timmorain Road', FALSE, FALSE, FALSE, 'outdoor'),
(5832, 4, 'Timmorain Road', FALSE, FALSE, FALSE, 'outdoor'),
(5833, 4, 'Timmorain Road', FALSE, FALSE, FALSE, 'outdoor'),
(25637, 4, 'A Small Clearing', FALSE, FALSE, FALSE, 'outdoor'),
(10496, 5, 'Neartofar Road', FALSE, FALSE, FALSE, 'outdoor'),
(10497, 5, 'Neartofar Road', FALSE, FALSE, FALSE, 'outdoor'),
(10498, 5, 'Neartofar Road', FALSE, FALSE, FALSE, 'outdoor'),
(31443, 5, 'Neartofar Road', FALSE, FALSE, FALSE, 'outdoor'),
(31444, 5, 'Neartofar Road', FALSE, FALSE, FALSE, 'outdoor'),
(31445, 5, 'Neartofar Road', FALSE, FALSE, FALSE, 'outdoor'),
(31446, 5, 'Neartofar Road', FALSE, FALSE, FALSE, 'outdoor'),
(31447, 5, 'Neartofar Road', FALSE, FALSE, FALSE, 'outdoor'),
(31448, 5, 'Neartofar Road, Dam', FALSE, FALSE, FALSE, 'outdoor'),
(31449, 5, 'Neartofar Road, Dam', FALSE, FALSE, FALSE, 'outdoor'),
(31450, 5, 'Neartofar Road, Dam', FALSE, FALSE, FALSE, 'outdoor'),
(31451, 5, 'Neartofar Road', FALSE, FALSE, FALSE, 'outdoor'),
(31452, 5, 'Neartofar Road', FALSE, FALSE, FALSE, 'outdoor'),
(31453, 5, 'Neartofar Road', FALSE, FALSE, FALSE, 'outdoor'),
(31454, 5, 'Neartofar Road', FALSE, FALSE, FALSE, 'outdoor'),
(31455, 5, 'Neartofar Road', FALSE, FALSE, FALSE, 'outdoor'),
(31456, 5, 'Neartofar Road, Grassy Field', FALSE, FALSE, FALSE, 'outdoor'),
(31457, 5, 'Shadowed Forest, Trail', FALSE, FALSE, FALSE, 'outdoor'),
(31458, 5, 'Shadowed Forest, Trail', FALSE, FALSE, FALSE, 'outdoor'),
(31459, 5, 'Shadowed Forest, Trail', FALSE, FALSE, FALSE, 'outdoor'),
(31460, 5, 'Shadowed Forest, Trail', FALSE, FALSE, FALSE, 'outdoor'),
(31461, 5, 'Shadowed Forest, Trail', FALSE, FALSE, FALSE, 'outdoor'),
(31462, 5, 'Shadowed Forest, Trail', FALSE, FALSE, FALSE, 'outdoor'),
(31463, 5, 'Shadowed Forest, Trail', FALSE, FALSE, FALSE, 'outdoor'),
(31464, 5, 'Shadowed Forest, Trail', FALSE, FALSE, FALSE, 'outdoor'),
(31465, 5, 'Ironwood Tree, Clearing', FALSE, FALSE, FALSE, 'outdoor'),
(31466, 5, 'Shadowed Forest, Trail', FALSE, FALSE, FALSE, 'outdoor'),
(31467, 5, 'Shadowed Forest, Trail', FALSE, FALSE, FALSE, 'outdoor'),
(31468, 5, 'Shadowed Forest, Trail', FALSE, FALSE, FALSE, 'outdoor'),
(31469, 5, 'Shadowed Forest, Trail', FALSE, FALSE, FALSE, 'outdoor'),
(31470, 5, 'Shadowed Forest, Trail', FALSE, FALSE, FALSE, 'outdoor'),
(31471, 5, 'Shadowed Forest, Trail', FALSE, FALSE, FALSE, 'outdoor'),
(31472, 5, 'Shadowed Forest, Trail', FALSE, FALSE, FALSE, 'outdoor'),
(31473, 5, 'Oceanside Forest, Clearing', FALSE, FALSE, FALSE, 'outdoor'),
(31474, 5, 'Oceanside Forest, Trail', FALSE, FALSE, FALSE, 'outdoor'),
(31475, 5, 'Oceanside Forest, Trail', FALSE, FALSE, FALSE, 'outdoor'),
(31476, 5, 'Oceanside Forest, Trail', FALSE, FALSE, FALSE, 'outdoor'),
(31477, 5, 'Oceanside Forest, Trail', FALSE, FALSE, FALSE, 'outdoor'),
(31478, 5, 'Oceanside Forest, Trail', FALSE, FALSE, FALSE, 'outdoor'),
(31479, 5, 'Oceanside Forest, Trail', FALSE, FALSE, FALSE, 'outdoor'),
(31480, 5, 'Oceanside Forest, Trail', FALSE, FALSE, FALSE, 'outdoor'),
(31481, 5, 'Oceanside Forest, Trail', FALSE, FALSE, FALSE, 'outdoor'),
(31482, 5, 'Oceanside Forest, Trail', FALSE, FALSE, FALSE, 'outdoor'),
(31483, 5, 'Oceanside Forest, Clearing', FALSE, FALSE, FALSE, 'outdoor'),
(31519, 5, 'Lasimor Clearing', TRUE, FALSE, FALSE, 'outdoor'),

(31520, 5, 'Lasimor Circle', TRUE, FALSE, FALSE, 'outdoor'),
(31521, 5, 'Lasimor Circle', TRUE, FALSE, FALSE, 'outdoor'),
(31522, 5, 'Lasimor Circle', TRUE, FALSE, FALSE, 'outdoor'),
(34448, 5, 'Neartofar Forest, Path', FALSE, FALSE, FALSE, 'outdoor'),
(34449, 5, 'Neartofar Forest, Path', FALSE, FALSE, FALSE, 'outdoor'),
(34450, 5, 'Neartofar Forest, Path', FALSE, FALSE, FALSE, 'outdoor'),
(34451, 5, 'Yasrenila Compound, Entrance', TRUE, FALSE, FALSE, 'outdoor'),
(34452, 5, 'Yasrenila, Honeybee Circle', TRUE, FALSE, FALSE, 'outdoor'),
(34453, 5, 'Yasrenila, Honeybee Circle', TRUE, FALSE, FALSE, 'outdoor'),
(34454, 5, 'Yasrenila, Imaera''s Alcove', TRUE, FALSE, TRUE, 'outdoor'),
(34455, 5, 'Yasrenila, Wisteria Walk', TRUE, FALSE, FALSE, 'outdoor'),
(34456, 5, 'Yasrenila, Honeybee Circle', TRUE, FALSE, FALSE, 'outdoor'),
(34457, 5, 'Honeycomb Hodgepodge', TRUE, FALSE, TRUE, 'outdoor'),
(34458, 5, 'Woodland Whimsy', TRUE, FALSE, TRUE, 'outdoor'),
(34459, 5, 'Yasrenila, Starling Round', TRUE, FALSE, FALSE, 'outdoor'),
(34460, 5, 'Yasrenila, Starling Round', TRUE, FALSE, FALSE, 'outdoor'),
(34461, 5, 'Yasrenila, Starling Round', TRUE, FALSE, FALSE, 'outdoor'),
(34462, 5, 'Freshly Foraged', TRUE, FALSE, TRUE, 'outdoor'),
(34463, 5, 'Freshly Foraged, Pergola', TRUE, FALSE, TRUE, 'outdoor'),
(34464, 5, 'Bee-utimous', TRUE, FALSE, TRUE, 'outdoor'),
(34465, 5, 'Yasrenila, Starling Round', TRUE, FALSE, FALSE, 'outdoor'),
(10622, 6, 'Neartofar Forest', FALSE, FALSE, FALSE, 'outdoor'),
(10623, 6, 'Neartofar Forest', FALSE, FALSE, FALSE, 'outdoor'),
(10624, 6, 'Neartofar Forest', FALSE, FALSE, FALSE, 'outdoor'),
(10625, 6, 'Neartofar Forest', FALSE, FALSE, FALSE, 'outdoor'),
(10626, 6, 'Neartofar Forest', FALSE, FALSE, FALSE, 'outdoor'),
(10627, 6, 'Neartofar Forest', FALSE, FALSE, FALSE, 'outdoor'),
(10628, 6, 'Neartofar Forest', FALSE, FALSE, FALSE, 'outdoor'),
(10629, 6, 'Neartofar Forest, Riverside', FALSE, FALSE, FALSE, 'outdoor'),
(10630, 6, 'Neartofar Forest, Riverside', FALSE, FALSE, FALSE, 'outdoor'),
(10631, 6, 'Neartofar Forest, Riverside', FALSE, FALSE, FALSE, 'outdoor'),
(10632, 6, 'Neartofar Forest, Riverside', FALSE, FALSE, FALSE, 'outdoor'),
(10633, 6, 'Neartofar Forest', FALSE, FALSE, FALSE, 'outdoor'),
(10634, 6, 'Neartofar Forest', FALSE, FALSE, FALSE, 'outdoor'),
(10635, 6, 'Neartofar Forest', FALSE, FALSE, FALSE, 'outdoor'),
(10636, 6, 'Neartofar Forest', FALSE, FALSE, FALSE, 'outdoor'),
(10637, 6, 'Neartofar Forest', FALSE, FALSE, FALSE, 'outdoor'),
(10638, 6, 'Neartofar Forest, Ridge', FALSE, FALSE, FALSE, 'outdoor'),
(10639, 6, 'Neartofar Forest, Ridge', FALSE, FALSE, FALSE, 'outdoor'),
(10640, 6, 'Neartofar Forest, Ridge', FALSE, FALSE, FALSE, 'outdoor'),
(10641, 6, 'Neartofar Forest, Ridge', FALSE, FALSE, FALSE, 'outdoor'),
(10642, 6, 'Neartofar Forest', FALSE, FALSE, FALSE, 'outdoor'),
(10643, 6, 'Neartofar Forest, Hillside', FALSE, FALSE, FALSE, 'outdoor'),
(10644, 6, 'Neartofar Forest, Hillside', FALSE, FALSE, FALSE, 'outdoor'),
(10645, 6, 'Neartofar Forest', FALSE, FALSE, FALSE, 'outdoor'),
(10646, 6, 'Neartofar Forest', FALSE, FALSE, FALSE, 'outdoor'),
(10647, 6, 'Neartofar Forest', FALSE, FALSE, FALSE, 'outdoor'),
(10648, 6, 'Neartofar Forest', FALSE, FALSE, FALSE, 'outdoor'),
(10649, 6, 'Neartofar Forest', FALSE, FALSE, FALSE, 'outdoor'),
(10650, 6, 'Neartofar Forest', FALSE, FALSE, FALSE, 'outdoor'),

(10651, 6, 'Neartofar Forest', FALSE, FALSE, FALSE, 'outdoor'),
(10652, 6, 'Neartofar Forest', FALSE, FALSE, FALSE, 'outdoor'),
(10653, 6, 'Neartofar Forest', FALSE, FALSE, FALSE, 'outdoor'),
(10654, 6, 'Neartofar Forest', FALSE, FALSE, FALSE, 'outdoor'),
(10655, 6, 'Neartofar Forest', FALSE, FALSE, FALSE, 'outdoor'),
(10656, 6, 'Neartofar Forest, Hillside', FALSE, FALSE, FALSE, 'outdoor'),
(10657, 6, 'Neartofar Forest, Hillside', FALSE, FALSE, FALSE, 'outdoor'),
(10658, 6, 'Neartofar Forest', FALSE, FALSE, FALSE, 'outdoor'),
(10659, 6, 'Neartofar Forest', FALSE, FALSE, FALSE, 'outdoor'),
(10660, 6, 'Neartofar Forest, Stockade', FALSE, FALSE, FALSE, 'outdoor'),
(10661, 6, 'Neartofar Forest, Stockade', FALSE, FALSE, FALSE, 'outdoor'),
(10662, 6, 'Neartofar Forest, Stockade', FALSE, FALSE, FALSE, 'outdoor'),
(10663, 6, 'Neartofar Forest, Stockade', FALSE, FALSE, FALSE, 'outdoor'),
(10664, 6, 'Neartofar Forest, Stockade', FALSE, FALSE, FALSE, 'outdoor'),
(10665, 6, 'Neartofar Forest, Stockade', FALSE, FALSE, FALSE, 'outdoor'),
(10666, 6, 'Neartofar Forest, Stockade', FALSE, FALSE, FALSE, 'outdoor'),
(10667, 6, 'Neartofar Forest, Stockade', FALSE, FALSE, FALSE, 'outdoor'),
(10668, 6, 'Neartofar Forest, Barracks', FALSE, FALSE, TRUE, 'outdoor'),
(10669, 6, 'Neartofar Forest, Barracks', FALSE, FALSE, TRUE, 'outdoor'),
(10670, 6, 'Neartofar Forest, Barracks', FALSE, FALSE, TRUE, 'outdoor'),
(10671, 6, 'Neartofar Forest, Barracks', FALSE, FALSE, TRUE, 'outdoor'),
(10499, 7, 'The Toadwort, Muddy Path', FALSE, FALSE, FALSE, 'outdoor'),
(10500, 7, 'The Toadwort, Muddy Path', FALSE, FALSE, FALSE, 'outdoor'),
(10501, 7, 'The Toadwort, Muddy Path', FALSE, FALSE, FALSE, 'outdoor'),
(10502, 7, 'The Toadwort, Muddy Path', FALSE, FALSE, FALSE, 'outdoor'),
(10503, 7, 'The Toadwort, Muddy Path', FALSE, FALSE, FALSE, 'outdoor'),
(10504, 7, 'The Toadwort, Muddy Path', FALSE, FALSE, FALSE, 'outdoor'),
(10505, 7, 'The Toadwort, Grasping Mire', FALSE, FALSE, FALSE, 'outdoor'),
(10506, 7, 'The Toadwort, Grasping Mire', FALSE, FALSE, FALSE, 'outdoor'),
(10507, 7, 'The Toadwort, Grasping Mire', FALSE, FALSE, FALSE, 'outdoor'),
(10508, 7, 'The Toadwort, Grasping Mire', FALSE, FALSE, FALSE, 'outdoor'),
(10509, 7, 'The Toadwort, Grasping Mire', FALSE, FALSE, FALSE, 'outdoor'),
(10510, 7, 'The Toadwort, Grasping Mire', FALSE, FALSE, FALSE, 'outdoor'),
(10511, 7, 'The Toadwort, Grasping Mire', FALSE, FALSE, FALSE, 'outdoor'),
(10512, 7, 'The Toadwort, Grasping Mire', FALSE, FALSE, FALSE, 'outdoor'),
(10513, 7, 'The Toadwort, Grasping Mire', FALSE, FALSE, FALSE, 'outdoor'),
(10514, 7, 'The Toadwort, Grasping Mire', FALSE, FALSE, FALSE, 'outdoor'),
(10515, 7, 'The Toadwort, Grasping Mire', FALSE, FALSE, FALSE, 'outdoor'),
(10516, 7, 'The Toadwort, Grasping Mire', FALSE, FALSE, FALSE, 'outdoor'),
(10517, 7, 'The Toadwort, Grasping Mire', FALSE, FALSE, FALSE, 'outdoor'),
(10518, 7, 'The Toadwort, Fetid Muck', FALSE, FALSE, FALSE, 'outdoor'),
(10519, 7, 'The Toadwort, Fetid Muck', FALSE, FALSE, FALSE, 'outdoor'),
(10520, 7, 'The Toadwort, Fetid Muck', FALSE, FALSE, FALSE, 'outdoor'),
(10521, 7, 'The Toadwort, Fetid Muck', FALSE, FALSE, FALSE, 'outdoor'),
(10522, 7, 'The Toadwort, Fetid Muck', FALSE, FALSE, FALSE, 'outdoor'),
(10523, 7, 'The Toadwort, Fetid Muck', FALSE, FALSE, FALSE, 'outdoor'),
(10524, 7, 'The Toadwort, Fetid Muck', FALSE, FALSE, FALSE, 'outdoor'),
(10525, 7, 'The Toadwort, Fetid Muck', FALSE, FALSE, FALSE, 'outdoor'),
(10526, 7, 'The Toadwort, Fetid Muck', FALSE, FALSE, FALSE, 'outdoor'),
(10527, 7, 'The Toadwort, Fetid Muck', FALSE, FALSE, FALSE, 'outdoor'),

(10528, 7, 'The Toadwort, Fetid Muck', FALSE, FALSE, FALSE, 'outdoor'),
(10529, 7, 'The Toadwort, Fetid Muck', FALSE, FALSE, FALSE, 'outdoor'),
(10530, 7, 'The Toadwort, Fetid Muck', FALSE, FALSE, FALSE, 'outdoor'),
(10531, 7, 'The Toadwort, Blackened Morass', FALSE, FALSE, FALSE, 'outdoor'),
(10532, 7, 'The Toadwort, Blackened Morass', FALSE, FALSE, FALSE, 'outdoor'),
(10533, 7, 'The Toadwort, Blackened Morass', FALSE, FALSE, FALSE, 'outdoor'),
(10534, 7, 'The Toadwort, Blackened Morass', FALSE, FALSE, FALSE, 'outdoor'),
(10535, 7, 'The Toadwort, Blackened Morass', FALSE, FALSE, FALSE, 'outdoor'),
(10536, 7, 'The Toadwort, Blackened Morass', FALSE, FALSE, FALSE, 'outdoor'),
(10537, 7, 'The Toadwort, Blackened Morass', FALSE, FALSE, FALSE, 'outdoor'),
(10538, 7, 'The Toadwort, Blackened Morass', FALSE, FALSE, FALSE, 'outdoor'),
(10539, 7, 'The Toadwort, Blackened Morass', FALSE, FALSE, FALSE, 'outdoor'),
(10540, 8, 'Lunule Weald, Slade', FALSE, FALSE, FALSE, 'outdoor'),
(10541, 8, 'Lunule Weald, Slade', FALSE, FALSE, FALSE, 'outdoor'),
(10542, 8, 'Lunule Weald, Slade', FALSE, FALSE, FALSE, 'outdoor'),
(10543, 8, 'Lunule Weald, Slade', FALSE, FALSE, FALSE, 'outdoor'),
(10544, 8, 'Lunule Weald, Slade', FALSE, FALSE, FALSE, 'outdoor'),
(10545, 8, 'Lunule Weald, Knoll', FALSE, FALSE, FALSE, 'outdoor'),
(10546, 8, 'Lunule Weald, Knoll', FALSE, FALSE, FALSE, 'outdoor'),
(10547, 8, 'Lunule Weald, Felwood Grove', FALSE, FALSE, FALSE, 'outdoor'),
(10548, 8, 'Lunule Weald, Slade', FALSE, FALSE, FALSE, 'outdoor'),
(10549, 8, 'Lunule Weald, Slade', FALSE, FALSE, FALSE, 'outdoor'),
(10550, 8, 'Lunule Weald, Slade', FALSE, FALSE, FALSE, 'outdoor'),
(10551, 8, 'Lunule Weald, Slade', FALSE, FALSE, FALSE, 'outdoor'),
(10552, 8, 'Lunule Weald, Knoll', FALSE, FALSE, FALSE, 'outdoor'),
(10553, 8, 'Lunule Weald, Knoll', FALSE, FALSE, FALSE, 'outdoor'),
(10554, 8, 'Lunule Weald, Knoll', FALSE, FALSE, FALSE, 'outdoor'),
(10555, 8, 'Lunule Weald, Knoll', FALSE, FALSE, FALSE, 'outdoor'),
(10556, 8, 'Lunule Weald, Slade', FALSE, FALSE, FALSE, 'outdoor'),
(10557, 8, 'Lunule Weald, Slade', FALSE, FALSE, FALSE, 'outdoor'),
(10558, 8, 'Lunule Weald, Slade', FALSE, FALSE, FALSE, 'outdoor'),
(10559, 8, 'Lunule Weald, Felwood Grove', FALSE, FALSE, FALSE, 'outdoor'),
(10560, 8, 'Lunule Weald, Felwood Grove', FALSE, FALSE, FALSE, 'outdoor'),
(10561, 8, 'Lunule Weald, Felwood Grove', FALSE, FALSE, FALSE, 'outdoor'),
(10562, 8, 'Lunule Weald, Felwood Grove', FALSE, FALSE, FALSE, 'outdoor'),
(10563, 8, 'Lunule Weald, Felwood Grove', FALSE, FALSE, FALSE, 'outdoor'),
(10564, 8, 'Lunule Weald, Felwood Grove', FALSE, FALSE, FALSE, 'outdoor'),
(10565, 8, 'Lunule Weald, Felwood Grove', FALSE, FALSE, FALSE, 'outdoor'),
(10566, 8, 'Lunule Weald, Felwood Grove', FALSE, FALSE, FALSE, 'outdoor'),
(10567, 8, 'Lunule Weald, Felwood Grove', FALSE, FALSE, FALSE, 'outdoor'),
(10568, 8, 'Lunule Weald, Felwood Grove', FALSE, FALSE, FALSE, 'outdoor'),
(10569, 8, 'Lunule Weald, Felwood Grove', FALSE, FALSE, FALSE, 'outdoor'),
(10570, 8, 'Lunule Weald, Felwood Grove', FALSE, FALSE, FALSE, 'outdoor'),
(10571, 8, 'Lunule Weald, Felwood Grove', FALSE, FALSE, FALSE, 'outdoor'),
(10572, 8, 'Lunule Weald, Felwood Grove', FALSE, FALSE, FALSE, 'outdoor'),
(10573, 8, 'Lunule Weald, Felwood Grove', FALSE, FALSE, FALSE, 'outdoor'),
(10574, 8, 'Lunule Weald, Felwood Grove', FALSE, FALSE, FALSE, 'outdoor'),
(10575, 8, 'Lunule Weald, Felwood Grove', FALSE, FALSE, FALSE, 'outdoor'),
(10576, 8, 'Lunule Weald, Felwood Grove', FALSE, FALSE, FALSE, 'outdoor'),
(10577, 8, 'Lunule Weald, Felwood Grove', FALSE, FALSE, FALSE, 'outdoor'),

(10578, 8, 'Lunule Weald, Perish Glen', FALSE, FALSE, FALSE, 'outdoor'),
(10579, 8, 'Lunule Weald, Perish Glen', FALSE, FALSE, FALSE, 'outdoor'),
(10580, 8, 'Lunule Weald, Perish Glen', FALSE, FALSE, FALSE, 'outdoor'),
(10581, 8, 'Lunule Weald, Perish Glen', FALSE, FALSE, FALSE, 'outdoor'),
(10582, 8, 'Lunule Weald, Perish Glen', FALSE, FALSE, FALSE, 'outdoor'),
(10583, 8, 'Lunule Weald, Perish Glen', FALSE, FALSE, FALSE, 'outdoor'),
(10584, 8, 'Lunule Weald, Perish Glen', FALSE, FALSE, FALSE, 'outdoor'),
(10585, 8, 'Lunule Weald, Perish Glen', FALSE, FALSE, FALSE, 'outdoor'),
(10586, 8, 'Lunule Weald, Perish Glen', FALSE, FALSE, FALSE, 'outdoor'),
(10587, 8, 'Lunule Weald, Perish Glen', FALSE, FALSE, FALSE, 'outdoor'),
(10588, 8, 'Lunule Weald, Perish Glen', FALSE, FALSE, FALSE, 'outdoor'),
(10589, 8, 'Lunule Weald, Perish Glen', FALSE, FALSE, FALSE, 'outdoor'),
(10590, 8, 'Lunule Weald, Perish Glen', FALSE, FALSE, FALSE, 'outdoor'),
(10591, 8, 'Lunule Weald, Perish Glen', FALSE, FALSE, FALSE, 'outdoor'),
(10592, 8, 'Lunule Weald, Perish Glen', FALSE, FALSE, FALSE, 'outdoor'),
(10593, 8, 'Lunule Weald, Perish Glen', FALSE, FALSE, FALSE, 'outdoor'),
(10594, 8, 'Lunule Weald, Perish Glen', FALSE, FALSE, FALSE, 'outdoor'),
(10595, 8, 'Lunule Weald, Perish Glen', FALSE, FALSE, FALSE, 'outdoor'),
(10596, 8, 'Lunule Weald, Zelia''s Shrine', FALSE, FALSE, TRUE, 'outdoor'),
(10597, 8, 'Lunule Weald, Zealot Village', FALSE, FALSE, FALSE, 'outdoor'),
(10598, 8, 'Lunule Weald, Zealot Village', FALSE, FALSE, FALSE, 'outdoor'),
(10599, 8, 'Lunule Weald, Zealot Village', FALSE, FALSE, FALSE, 'outdoor'),
(10600, 8, 'Lunule Weald, Zealot Village', FALSE, FALSE, FALSE, 'outdoor'),
(10601, 8, 'Lunule Weald, Zealot Village', FALSE, FALSE, FALSE, 'outdoor'),
(10602, 8, 'Lunule Weald, Zealot Village', FALSE, FALSE, FALSE, 'outdoor'),
(10603, 8, 'Lunule Weald, Zealot Village', FALSE, FALSE, FALSE, 'outdoor'),
(10604, 8, 'Lunule Weald, Zealot Village', FALSE, FALSE, FALSE, 'outdoor'),
(10605, 8, 'Lunule Weald, Zealot Village', FALSE, FALSE, FALSE, 'outdoor'),
(10606, 8, 'Lunule Weald, Zealot Village', FALSE, FALSE, FALSE, 'outdoor'),
(10607, 8, 'Lunule Weald, Zealot Village', FALSE, FALSE, TRUE, 'outdoor'),
(10608, 8, 'Lunule Weald, Zealot Village', FALSE, FALSE, TRUE, 'outdoor'),
(10609, 8, 'Lunule Weald, Zealot Village', FALSE, FALSE, TRUE, 'outdoor'),
(10610, 8, 'Lunule Weald, Perish Glen', FALSE, FALSE, FALSE, 'outdoor'),
(10611, 8, 'Lunule Weald, Zealot Village', FALSE, FALSE, FALSE, 'outdoor'),
(10612, 8, 'Lunule Weald, Zealot Village', FALSE, FALSE, FALSE, 'outdoor'),
(10613, 8, 'Lunule Weald, Zealot Village', FALSE, FALSE, FALSE, 'outdoor'),
(10614, 8, 'Lunule Weald, Zealot Village', FALSE, FALSE, FALSE, 'outdoor'),
(10615, 8, 'Lunule Weald, Zealot Village', FALSE, FALSE, FALSE, 'outdoor'),
(10616, 8, 'Lunule Weald, Zealot Village', FALSE, FALSE, FALSE, 'outdoor'),
(10617, 8, 'Lunule Weald, Zealot Village', FALSE, FALSE, FALSE, 'outdoor'),
(10618, 8, 'Lunule Weald, Zealot Village', FALSE, FALSE, FALSE, 'outdoor'),
(10619, 8, 'Lunule Weald, Zealot Village', FALSE, FALSE, FALSE, 'outdoor'),
(10620, 8, 'Lunule Weald, Zealot Village', FALSE, FALSE, FALSE, 'outdoor'),
(10621, 8, 'Lunule Weald, Zealot Village', FALSE, FALSE, FALSE, 'outdoor')
ON DUPLICATE KEY UPDATE title=VALUES(title), zone_id=VALUES(zone_id);