-- =============================================================================
-- scripts/combat_maneuvers/definitions.lua
-- Generated from the live Combat Maneuvers list plus cached maneuver page data.
-- Lua is the source of truth for maneuver metadata and catalog behavior.
-- =============================================================================

local Maneuvers = {}
local ALL_PROFESSIONS = { "warrior", "rogue", "wizard", "cleric", "empath", "sorcerer", "ranger", "bard", "paladin", "monk" }

local function def(t)
    return t
end

Maneuvers['acrobatsleap'] = def {
    mnemonic        = 'acrobatsleap',
    name            = 'Acrobat\'s Leap',
    type            = 'passive',
    raw_type        = 'Passive',
    category        = 'general',
    raw_category    = '',
    family          = 'passive',
    handler_key     = 'acrobatsleap',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '',
    offensive_gear  = '',
    requirements    = '',
    description     = 'Your acrobatics training taught you to make minor leaps in combat to increase your reach.',
    mechanics       = 'Your reach is increased by {{mono|(1 + ([[agility]] bonus / 10))}} feet while [[ambush]]ing or using [[maneuver]]s that take the height system into account.  Every 30% of [[encumbrance]] reduces your reach by 1 foot.  Every [[Armor|Armor Group]] over scale reduces your reach by 1 foot.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 1,
    rank_costs      = { 10, 0, 0, 0, 0 },
    available_to    = { "warrior", "rogue", "ranger", "monk" },
}

Maneuvers['bearhug'] = def {
    mnemonic        = 'bearhug',
    name            = 'Bearhug',
    type            = 'concentration',
    raw_type        = 'Concentration',
    category        = 'general',
    raw_category    = '',
    family          = 'concentration',
    handler_key     = 'bearhug',
    targeting       = 'current_target',
    roundtime       = 'Varies',
    stamina         = '10',
    offensive_gear  = 'Arm accessory, or armor covering the arms',
    requirements    = '',
    description     = 'Attempt to grab your foe and squeeze them to death.',
    mechanics       = 'Maneuver a target with three rounds of heavy concussion damage.  If the target is [[Vulnerable]], this skill becomes empowered and is quicker.  Upon success, you and your party gain [[Enhance (effect)|Enhance Strength]] with a power of 10 for 2 minutes.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "monk" },
}

Maneuvers['berserk'] = def {
    mnemonic        = 'berserk',
    name            = 'Berserk',
    type            = 'attack',
    raw_type        = 'Attack',
    category        = 'warrior_guild',
    raw_category    = 'Warrior Guild',
    family          = 'attack',
    handler_key     = 'berserk',
    targeting       = 'current_target',
    roundtime       = 'ATTACK-1',
    stamina         = '20.  There is an additional cost of 10 per round.',
    offensive_gear  = 'Both hands',
    requirements    = '',
    description     = 'Attempt to go into a blind berserker rage.',
    mechanics       = 'Temporarily lose control of your combat actions and attack any target within range every five seconds.  You gain a bonus of {{mono|(Rank * 5)}} to your [[attack strength|Attack Strength (AS)]].  If you are [[stunned]], [[webbed]], or [[Bind (214)|bound]] during the course of your berserk, you will attempt to break these hindrances.  You may also attempt to start a berserk while in one of those states.',
    is_guild_skill  = true,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 3, 4, 5, 6 },
    available_to    = { "warrior" },
}

Maneuvers['blockspec'] = def {
    mnemonic        = 'blockspec',
    name            = 'Block Specialization',
    type            = 'passive',
    raw_type        = 'Passive',
    category        = 'general',
    raw_category    = '',
    family          = 'passive',
    handler_key     = 'blockspec',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '',
    offensive_gear  = '',
    requirements    = '',
    description     = 'You specialize in blocking attacks with a [[shield]].',
    mechanics       = 'Increase your [[block]] chance by 5% per rank.  You have a {{mono|(10 + (5 * Rank))%}} chance to gain [[Defensive Posture]] when blocking an attack in an aggressive [[stance]].  Only one of Block Specialization, [[Evade Specialization]], or [[Parry Specialization]] may be trained.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 3,
    rank_costs      = { 4, 8, 12, 0, 0 },
    available_to    = { "warrior", "rogue", "monk" },
}

Maneuvers['bullrush'] = def {
    mnemonic        = 'bullrush',
    name            = 'Bull Rush',
    type            = 'aoe',
    raw_type        = 'Area of Effect',
    category        = 'general',
    raw_category    = '',
    family          = 'aoe',
    handler_key     = 'bullrush',
    targeting       = 'current_target_optional',
    roundtime       = '4s',
    stamina         = '14',
    offensive_gear  = 'Arm accessory, or armor covering the arms',
    requirements    = '',
    description     = 'Attempt to rush your opponent and send them careening into one another, knocking them down and sowing havoc on the battlefield.',
    mechanics       = 'Maneuver a target causing minor [[impact critical table|impact]] damage and send them into other targets, causing moderate [[unbalance critical table|unbalance]] damage.  Applies [[Vulnerable]] for {{mono|(15 + (Rank * 5))}} seconds and [[Staggered]] for {{mono|(5 + (Success Margin / 6))}} seconds to any target hit.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "monk", "paladin" },
}

Maneuvers['burst'] = def {
    mnemonic        = 'burst',
    name            = 'Burst of Swiftness',
    type            = 'buff',
    raw_type        = 'Buff',
    category        = 'general',
    raw_category    = '',
    family          = 'buff',
    handler_key     = 'burst',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '30',
    offensive_gear  = '',
    requirements    = '',
    description     = 'Dig deep for a Burst of Swiftness.',
    mechanics       = 'Apply [[Enhance (effect)|Enhance Agility]] with a power of {{mono|(12 + (4 * Rank))}} and [[Enhance (effect)|Enhance Dexterity]] with a power of {{mono|(6 + (2 * Rank))}} for 90 seconds (refreshable).',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "monk" },
}

Maneuvers['cheapshots'] = def {
    mnemonic        = 'cheapshots',
    name            = 'Cheapshots',
    type            = 'setup',
    raw_type        = 'Setup',
    category        = 'rogue_guild',
    raw_category    = 'Rogue Guild',
    family          = 'setup',
    handler_key     = 'cheapshots',
    targeting       = 'current_target',
    roundtime       = '2s',
    stamina         = '7',
    offensive_gear  = '',
    requirements    = '',
    description     = 'Various quick and dirty maneuvers.',
    mechanics       = 'Learning cheapshots will automatically grant you the following skills:',
    is_guild_skill  = true,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "rogue", "bard", "monk" },
}

Maneuvers['focus'] = def {
    mnemonic        = 'focus',
    name            = 'Combat Focus',
    type            = 'passive',
    raw_type        = 'Passive',
    category        = 'general',
    raw_category    = '',
    family          = 'passive',
    handler_key     = 'focus',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '',
    offensive_gear  = '',
    requirements    = '',
    description     = 'Your training has improved your ability to defend against spells.',
    mechanics       = '+2 per rank to generic [[Target Defense|TD]].',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "rogue", "ranger", "bard", "monk", "paladin" },
}

Maneuvers['mobility'] = def {
    mnemonic        = 'mobility',
    name            = 'Combat Mobility',
    type            = 'passive',
    raw_type        = 'Passive',
    category        = 'general',
    raw_category    = '',
    family          = 'passive',
    handler_key     = 'mobility',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '',
    offensive_gear  = '',
    requirements    = '',
    description     = 'Your quick reflexes allow you to quickly stand up when attacked.',
    mechanics       = 'The Combat Mobility maneuver works automatically when you are attacked.  If you are not in a standing position, you will automatically attempt to stand up before your opponent can attack you.  Combat Mobility will not activate if you are [[stunned]], [[webbed]], [[Bind (214)|bound]], or otherwise [[immobilized]].  However, it will activate if you are free of these hindrances, even if you are in [[roundtime]].  This maneuver costs no [[stamina]] to activate.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 1,
    rank_costs      = { 10, 0, 0, 0, 0 },
    available_to    = { "warrior", "rogue", "monk" },
}

Maneuvers['cmovement'] = def {
    mnemonic        = 'cmovement',
    name            = 'Combat Movement',
    type            = 'passive',
    raw_type        = 'Passive',
    category        = 'general',
    raw_category    = '',
    family          = 'passive',
    handler_key     = 'cmovement',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '',
    offensive_gear  = '',
    requirements    = '',
    description     = 'Your training has improved your ability to defend against attacks.',
    mechanics       = '+2 per rank to physical DS.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 3, 4, 5, 6 },
    available_to    = { "warrior", "rogue", "wizard", "cleric", "empath", "sorcerer", "ranger", "bard", "paladin", "monk" },
}

Maneuvers['toughness'] = def {
    mnemonic        = 'toughness',
    name            = 'Combat Toughness',
    type            = 'passive',
    raw_type        = 'Passive',
    category        = 'general',
    raw_category    = '',
    family          = 'passive',
    handler_key     = 'toughness',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '',
    offensive_gear  = '',
    requirements    = '',
    description     = 'Combat has made you more resilient.',
    mechanics       = 'Permanently enhances your maximum number of [[Health|Health Points (HP)]] by 5 plus 10 points per rank.  For clarity, you receive 5+10 at Rank 1, 10 at Rank 2.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 3,
    rank_costs      = { 6, 8, 10, 0, 0 },
    available_to    = { "warrior", "rogue", "ranger", "monk", "paladin" },
}

Maneuvers['coupdegrace'] = def {
    mnemonic        = 'coupdegrace',
    name            = 'Coup de Grace',
    type            = 'attack',
    raw_type        = 'Attack',
    category        = 'general',
    raw_category    = '',
    family          = 'attack',
    handler_key     = 'coupdegrace',
    targeting       = 'current_target',
    roundtime       = 'ATTACK',
    stamina         = '20',
    offensive_gear  = 'Both hands',
    requirements    = '',
    description     = 'Attempt to finish off a weakened enemy.',
    mechanics       = 'Maneuver a target, resulting in their immediate [[death]].  The target must be incapacitated in some way, and have {{mono|(Rank * 10)%}} or lower [[health]] (200 max).  Alternatively, the target may have {{mono|(Rank * 5)%}} or lower health (200 max) without being incapacitated.  Applies [[Empowered]] with a power of {{mono|(Success Margin / 5)}} to the player and player\'s party for 90 seconds, and [[Demoralized]] with a power of {{mono|(Success Margin / 5)}} for 90 seconds to any hostile [[creature]]s in the room.',
    hotbar_ready    = {
        any_of = {
            {
                all_of = {
                    { kind = 'target_status_any', statuses = { 'stunned', 'dazed', 'prone', 'webbed', 'rooted', 'immobile', 'immobilized', 'bound', 'pinned', 'staggered', 'disoriented', 'vulnerable' } },
                    { kind = 'target_health_at_or_below', percent_per_rank = 10, max_health_cap = 200 },
                },
            },
            { kind = 'target_health_at_or_below', percent_per_rank = 5, max_health_cap = 200 },
        },
        message = 'That maneuver requires an incapacitated or badly weakened target.',
    },
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "rogue", "monk" },
}

Maneuvers['cpress'] = def {
    mnemonic        = 'cpress',
    name            = 'Crowd Press',
    type            = 'setup',
    raw_type        = 'Setup',
    category        = 'general',
    raw_category    = '',
    family          = 'setup',
    handler_key     = 'cpress',
    targeting       = 'current_target',
    roundtime       = '3s',
    stamina         = '9',
    offensive_gear  = '',
    requirements    = '',
    description     = 'Maneuver in close to an enemy to gain an advantage with small [[weapon]]s.',
    mechanics       = 'Maneuver a target, preventing the target from performing several actions.  Weapons with a base [[roundtime]] faster than 4 seconds will see improvements to [[Attack Strength]] and [[aim]]ing chance, weapon at 4 seconds will see no improvement or penalty, and weapons slower than 4 seconds will see a penalty.  Applies [[Pressed]] for {{mono|(15 + (Rank * 5))}} seconds.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "rogue", "monk" },
}

Maneuvers['cdefense'] = def {
    mnemonic        = 'cdefense',
    name            = 'Cunning Defense',
    type            = 'passive',
    raw_type        = 'Passive',
    category        = 'general',
    raw_category    = '',
    family          = 'passive',
    handler_key     = 'cdefense',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '',
    offensive_gear  = '',
    requirements    = '',
    description     = 'Your training has improved your ability to defend against maneuvers.',
    mechanics       = 'Grants phantom [[Dodging|dodge]] ranks for the purposes of [[SMRv2]] defense against PSM maneuvers.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 3, 4, 5, 6 },
    available_to    = { "warrior", "rogue", "wizard", "cleric", "empath", "sorcerer", "ranger", "bard", "paladin", "monk" },
}

Maneuvers['cutthroat'] = def {
    mnemonic        = 'cutthroat',
    name            = 'Cutthroat',
    type            = 'setup',
    raw_type        = 'Setup',
    category        = 'general',
    raw_category    = '',
    family          = 'setup',
    handler_key     = 'cutthroat',
    targeting       = 'current_target',
    roundtime       = '4s',
    stamina         = '14',
    offensive_gear  = 'Right hand',
    requirements    = '',
    description     = 'Spring from [[stealth|hiding]] and attempt to slit your target\'s throat.',
    mechanics       = 'Maneuver a target and deal significant neck damage.  Applies [[Major Bleed]] based on the damage done, and [[Silenced|Silences]] until the target dies or the associated neck [[wound]] is healed.',
    hotbar_ready    = { kind = 'player_hidden', message = 'You need to be hidden first.' },
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "rogue" },
}

Maneuvers['dirtkick'] = def {
    mnemonic        = 'dirtkick',
    name            = 'Dirtkick',
    type            = 'setup',
    raw_type        = 'Setup',
    category        = 'general',
    raw_category    = '',
    family          = 'setup',
    handler_key     = 'dirtkick',
    targeting       = 'current_target',
    roundtime       = '2s',
    stamina         = '7',
    offensive_gear  = '',
    requirements    = '',
    description     = 'Attempt to kick dirt into the face of an opponent.',
    mechanics       = 'Maneuver a target to apply [[Blinded]] for {{mono|(5 + (Success Margin / 10))}} seconds and [[Staggered]] for {{mono|(Success Margin / 7)}} seconds.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "rogue", "wizard", "cleric", "empath", "sorcerer", "ranger", "bard", "paladin", "monk" },
}

Maneuvers['disarm'] = def {
    mnemonic        = 'disarm',
    name            = 'Disarm Weapon',
    type            = 'setup',
    raw_type        = 'Setup',
    category        = 'warrior_guild',
    raw_category    = 'Warrior Guild',
    family          = 'setup',
    handler_key     = 'disarm',
    targeting       = 'current_target',
    roundtime       = '2s',
    stamina         = '7',
    offensive_gear  = 'Right hand',
    requirements    = 'A [[weapon]] to disarm with (Rank 5 masters may disarm bare-handed).',
    description     = 'Knock a target\'s [[weapon]] from their grasp.',
    mechanics       = 'Maneuver a target and attempt to disarm them.  Applies [[Staggered]] for {{mono|(Success Margin / 4)}} seconds.',
    is_guild_skill  = true,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "rogue", "wizard", "cleric", "empath", "sorcerer", "ranger", "bard", "paladin", "monk" },
}

Maneuvers['dislodge'] = def {
    mnemonic        = 'dislodge',
    name            = 'Dislodge',
    type            = 'setup',
    raw_type        = 'Setup',
    category        = 'general',
    raw_category    = '',
    family          = 'setup',
    handler_key     = 'dislodge',
    targeting       = 'current_target',
    roundtime       = '3s',
    stamina         = '9',
    offensive_gear  = '',
    requirements    = 'An empty hand.',
    description     = 'Attempt to violently retrieve ranged ammo or a [[hurl]]ed weapon that has been lodged in your target.',
    mechanics       = 'Maneuver a target, dealing moderate [[slash critical table|slashing]] damage.  Successful attempts will place the weapon in hand.  May be aimed via {{boldmono|CMAN DISLODGE {target} {body part}}}.  Each rank passively increases the chance that a successful [[Ranged Weapons|ranged]] or [[Thrown Weapons|thrown]] [[ attack]] will stick.  Applies [[Weakened Armament]] for {{mono|(15 + (Rank * 5))}} seconds.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "rogue", "ranger", "bard", "monk", "paladin" },
}

Maneuvers['divert'] = def {
    mnemonic        = 'divert',
    name            = 'Divert',
    type            = 'setup',
    raw_type        = 'Setup',
    category        = 'rogue_guild',
    raw_category    = 'Rogue Guild',
    family          = 'setup',
    handler_key     = 'divert',
    targeting       = 'current_target',
    roundtime       = '2s',
    stamina         = '7',
    offensive_gear  = '',
    requirements    = '',
    description     = 'From [[stealth|hiding]], you attempt to divert your foe\'s attention, luring them to an adjacent room.',
    mechanics       = ':{{boldmono|[[CMAN]] DIVERT {creature}}}             - Lure a foe to a random adjacent room.',
    is_guild_skill  = true,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 3, 4, 5, 6 },
    available_to    = { "rogue" },
}

Maneuvers['duckandweave'] = def {
    mnemonic        = 'duckandweave',
    name            = 'Duck and Weave',
    type            = 'martial_stance',
    raw_type        = 'Martial Stance',
    category        = 'general',
    raw_category    = '',
    family          = 'stance',
    handler_key     = 'duckandweave',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '20',
    offensive_gear  = '',
    requirements    = 'Training in [[Dodging]] and [[Multi-Opponent Combat]] is recommended.',
    description     = 'Redirect your enemies\' attacks to each other as you weave between them.',
    mechanics       = 'Upon evading a melee attack, there is a chance that the attack can be redirected against another enemy in the same room.  The chance for redirection is {{mono|((8 * (1 + Duck and Weave Ranks)) + (8 * Dodge Ranks per level) + (1 / 10) MoC ranks to 100 ranks + (1 / 20) MoC ranks over 100 + ((Agi Bonus + (2 * Inf Bonus)) / 5))}}.  Each stance higher than offensive reduces the redirection chance by 20%, and is removed entirely in defensive stance.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 3,
    rank_costs      = { 3, 6, 9, 0, 0 },
    available_to    = { "rogue", "monk" },
}

Maneuvers['shroud'] = def {
    mnemonic        = 'shroud',
    name            = 'Dust Shroud',
    type            = 'buff',
    raw_type        = 'Buff',
    category        = 'general',
    raw_category    = '',
    family          = 'buff',
    handler_key     = 'shroud',
    targeting       = 'none',
    roundtime       = 'HIDE',
    stamina         = '10',
    offensive_gear  = '',
    requirements    = 'Training in Stalking and Hiding is recommended.',
    description     = 'Kick up some dust to distract your opponents while you attempt to slip into [[Stealth|hiding]].',
    mechanics       = 'Instantly attempt to hide.  Applies [[Shrouded]] with a power of {{mono|(Rank * 15)}} for {{mono|(Rank + 5)}} seconds prior to the {{boldmono|[[HIDE]]}} attempt.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "rogue" },
}

Maneuvers['evadespec'] = def {
    mnemonic        = 'evadespec',
    name            = 'Evade Specialization',
    type            = 'passive',
    raw_type        = 'Passive',
    category        = 'general',
    raw_category    = '',
    family          = 'passive',
    handler_key     = 'evadespec',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '',
    offensive_gear  = '',
    requirements    = '',
    description     = 'You specialize in evading attacks before they can land.',
    mechanics       = 'Increase your [[evade]] chance by 5% per rank.  You have a {{mono|(10 + (5 * Rank))%}} chance to gain [[Evasiveness]] when evading an attack in an aggressive [[stance]].  Only one of [[Block Specialization]], Evade Specialization, or [[Parry Specialization]] may be trained.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 3,
    rank_costs      = { 4, 8, 12, 0, 0 },
    available_to    = { "warrior", "rogue", "monk" },
}

Maneuvers['eviscerate'] = def {
    mnemonic        = 'eviscerate',
    name            = 'Eviscerate',
    type            = 'aoe',
    raw_type        = 'Area of Effect',
    category        = 'general',
    raw_category    = '',
    family          = 'aoe',
    handler_key     = 'eviscerate',
    targeting       = 'current_target_optional',
    roundtime       = '4s',
    stamina         = '14',
    offensive_gear  = 'Right hand',
    requirements    = '',
    description     = 'Spring from hiding to surprise and terrify enemies.',
    mechanics       = 'Maneuver a target, dealing minor [[slash critical table|slashing]] damage and minor concussion damage.  Applies [[Major Bleed]] to the primary target.  Applies [[Terrified]] or [[Demoralized]] with a power of 15 to other targets that witness the attack.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "rogue" },
}

Maneuvers['executioner'] = def {
    mnemonic        = 'executioner',
    name            = 'Executioner\'s Stance',
    type            = 'martial_stance',
    raw_type        = 'Martial Stance',
    category        = 'general',
    raw_category    = '',
    family          = 'stance',
    handler_key     = 'executioner',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '20',
    offensive_gear  = '',
    requirements    = 'a [[Two-Handed Weapons|two-handed weapon]] or two-handed [[polearm]]',
    description     = 'Carry through the momentum of your killing blow to strike another target.',
    mechanics       = 'If you slay a creature with a two-handed [[weapon]] attack while in this stance, you have a chance to maintain your momentum and continue the attack onto another foe in the room.  This chance is {{mono|5% + 15%}} per rank.  The secondary attack will have an [[attack strength|AS]] penalty of -25 and cannot occur more than once per attack.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 3,
    rank_costs      = { 3, 6, 9, 0, 0 },
    available_to    = { "warrior" },
}

Maneuvers['exsanguinate'] = def {
    mnemonic        = 'exsanguinate',
    name            = 'Exsanguinate',
    type            = 'attack',
    raw_type        = 'Attack',
    category        = 'general',
    raw_category    = '',
    family          = 'attack',
    handler_key     = 'exsanguinate',
    targeting       = 'current_target',
    roundtime       = 'ATTACK-2',
    stamina         = '15',
    offensive_gear  = 'Both hands',
    requirements    = '',
    description     = 'Exploit your foe\'s existing wounds to bleed them dry.',
    mechanics       = 'Maneuver a target causing all remaining ticks of [[Major Bleed]] to trigger.  There is a {{mono|(Rank * 10)%}} chance of automatically reapplying the bleed at {{mono|(Success Margin / 5)%}} effectiveness.  Finally, you passively gain one additional round of Major Bleed at ranks 3 and 5 (up to 2 additional rounds).',
    hotbar_ready    = { kind = 'target_status_any', statuses = { 'bleeding', 'major_bleed' }, message = 'That maneuver requires a bleeding target.' },
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "rogue", "ranger", "bard", "monk", "paladin" },
}

Maneuvers['eyepoke'] = def {
    mnemonic        = 'eyepoke',
    name            = 'Eyepoke',
    type            = 'setup',
    raw_type        = 'Setup',
    category        = 'rogue_guild',
    raw_category    = 'Rogue Guild',
    family          = 'setup',
    handler_key     = 'eyepoke',
    targeting       = 'current_target',
    roundtime       = '2s',
    stamina         = '7',
    offensive_gear  = 'Gloves, or armor covering the hands',
    requirements    = '',
    description     = 'Attempt to temporarily blind an opponent.',
    mechanics       = 'Maneuver a target to apply [[Blinded]] for {{mono|(5 + (Success Margin / 6))}} seconds.',
    is_guild_skill  = true,
    is_learnable    = true,
    max_rank        = 1,
    rank_costs      = { 0, 0, 0, 0, 0 },
    available_to    = { "rogue", "bard", "monk" },
}

Maneuvers['feint'] = def {
    mnemonic        = 'feint',
    name            = 'Feint',
    type            = 'setup',
    raw_type        = 'Setup',
    category        = 'warrior_guild',
    raw_category    = 'Warrior Guild',
    family          = 'setup',
    handler_key     = 'feint',
    targeting       = 'current_target',
    roundtime       = '3s',
    stamina         = '9',
    offensive_gear  = 'Right hand',
    requirements    = 'a weapon to feint with (Rank 5 masters may feint bare-handed)',
    description     = 'Attempt to distract an opponent into dropping their stance.',
    mechanics       = 'Maneuver a target to reduce their [[stance]] by by 1% per [[endroll]] over 100.  An endroll of 200 will force the target to offensive.  Applies [[Staggered]] for {{mono|(Success Margin / 6)}} seconds.',
    is_guild_skill  = true,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "rogue", "wizard", "cleric", "empath", "sorcerer", "ranger", "bard", "paladin", "monk" },
}

Maneuvers['flurry'] = def {
    mnemonic        = 'flurry',
    name            = 'Flurry of Blows',
    type            = 'martial_stance',
    raw_type        = 'Martial Stance',
    category        = 'general',
    raw_category    = '',
    family          = 'stance',
    handler_key     = 'flurry',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '20',
    offensive_gear  = '',
    requirements    = '',
    description     = 'Find opportunities to follow up your [[JAB (verb)|jab]] attacks with additional jabs at other adjacent foes.',
    mechanics       = 'When under its effects, you automatically follow up on your jab attacks with additional jabs against other foes in the same area.  There is a 50% chance of making a second jab at rank 1, and a 75% chance at rank 2.  At rank 3, there is a 75% chance of making a second jab attack, and a 50% chance of a third jab if the second is successful.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 3,
    rank_costs      = { 3, 6, 9, 0, 0 },
    available_to    = { "monk" },
}

Maneuvers['footstomp'] = def {
    mnemonic        = 'footstomp',
    name            = 'Footstomp',
    type            = 'setup',
    raw_type        = 'Setup',
    category        = 'rogue_guild',
    raw_category    = 'Rogue Guild',
    family          = 'setup',
    handler_key     = 'footstomp',
    targeting       = 'current_target',
    roundtime       = '2s',
    stamina         = '7',
    offensive_gear  = 'Boots, or armor covering the feet',
    requirements    = '',
    description     = 'Stomp on an opponent\'s foot to delay their attacks.',
    mechanics       = 'Maneuver a target to apply [[Staggered]] for {{mono|(Success Margin / 6)}} seconds.',
    is_guild_skill  = true,
    is_learnable    = true,
    max_rank        = 1,
    rank_costs      = { 0, 0, 0, 0, 0 },
    available_to    = { "rogue", "bard", "monk" },
}

Maneuvers['garrote'] = def {
    mnemonic        = 'garrote',
    name            = 'Garrote',
    type            = 'concentration',
    raw_type        = 'Concentration',
    category        = 'general',
    raw_category    = '',
    family          = 'concentration',
    handler_key     = 'garrote',
    targeting       = 'current_target',
    roundtime       = 'Varies',
    stamina         = '10',
    offensive_gear  = '',
    requirements    = 'A suitable garrote item',
    description     = 'Garrote is used to strangle an opponent.',
    mechanics       = 'Maneuver a target over four rounds, leading to eventual strangulation.  If you are [[hidden]], this skill becomes empowered and is quicker. Upon success, you and your party gain [[Enhance (effect)|Enhance Agility]] with a power of 10 for 2 minutes.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "rogue", "ranger", "bard", "monk" },
}

Maneuvers['grapplespec'] = def {
    mnemonic        = 'grapplespec',
    name            = 'Grapple Specialization',
    type            = 'passive',
    raw_type        = 'Passive',
    category        = 'general',
    raw_category    = '',
    family          = 'passive',
    handler_key     = 'grapplespec',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '',
    offensive_gear  = '',
    requirements    = '',
    description     = 'You specialize in grappling during [[unarmed combat]].',
    mechanics       = 'When using {{boldmono|[[GRAPPLE]]}}, you gain {{mono|(Rank * 2)}} to [[Multiplier modifier|Multiplier Modifier (MM)]] and an additional {{mono|(Rank * 2)%}} chance to present a tier-up opening.  Only one of [[Punch Specialization]], [[Kick Specialization]], or Grapple Specialization may be trained.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "rogue", "monk" },
}

Maneuvers['griffin'] = def {
    mnemonic        = 'griffin',
    name            = 'Griffin\'s Voice',
    type            = 'martial_stance',
    raw_type        = 'Martial Stance',
    category        = 'general',
    raw_category    = '',
    family          = 'stance',
    handler_key     = 'griffin',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '20',
    offensive_gear  = '',
    requirements    = 'Training in the War Cries warrior guild skill.',
    description     = 'Gain greater control over your [[War Cries]], reducing vocal stress and affecting the [[undead]].',
    mechanics       = 'At rank 1, the [[stamina]] cost of each war cry is reduced by a third.  At rank 2, you will be able to affect the undead with your war cries.  At rank 3, the stamina cost of each war cry is instead reduced by half.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 3,
    rank_costs      = { 3, 6, 9, 0, 0 },
    available_to    = { "warrior" },
}

Maneuvers['gkick'] = def {
    mnemonic        = 'gkick',
    name            = 'Groin Kick',
    type            = 'setup',
    raw_type        = 'Setup',
    category        = 'general',
    raw_category    = '',
    family          = 'setup',
    handler_key     = 'gkick',
    targeting       = 'current_target',
    roundtime       = '2s',
    stamina         = '7',
    offensive_gear  = 'Leg accessory, or armor covering the legs',
    requirements    = '',
    description     = 'Attempts to land a kick to the opponent\'s groin, doing minor damage and possibly forcing the target to lose its concentration.',
    mechanics       = 'Maneuver a target to bring them to their knees.  Can reduce [[stance]] and cause loss of [[prepare]]d [[ spell]]s.  Applies [[Dazed]] to the target for {{mono|(5 + (Rank * 2))}} seconds and [[Staggered]] for {{mono|(Success Margin / 6)}} seconds.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "rogue", "wizard", "cleric", "empath", "sorcerer", "ranger", "bard", "paladin", "monk" },
}

Maneuvers['hamstring'] = def {
    mnemonic        = 'hamstring',
    name            = 'Hamstring',
    type            = 'setup',
    raw_type        = 'Setup',
    category        = 'general',
    raw_category    = '',
    family          = 'setup',
    handler_key     = 'hamstring',
    targeting       = 'current_target',
    roundtime       = '3s',
    stamina         = '9',
    offensive_gear  = 'Both hands',
    requirements    = 'A slashing weapon (that is not twohanded).',
    description     = 'Attempt to slice a target\'s hamstring muscle and knock them to the ground.',
    mechanics       = 'Maneuver a target to deliver up to a rank 2 leg [[wound]] and potentially knock them down.  Hamstring takes critical [[weighting]] or damage weighting on the [[weapon]] used into account. Padding, resistances, flares, armor divisors, and the like are all bypassed when the maneuver succeeds.  Applies [[Major Bleed]] based on the damage of the initial maneuver.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "rogue", "ranger", "bard", "monk" },
}

Maneuvers['haymaker'] = def {
    mnemonic        = 'haymaker',
    name            = 'Haymaker',
    type            = 'setup',
    raw_type        = 'Setup',
    category        = 'general',
    raw_category    = '',
    family          = 'setup',
    handler_key     = 'haymaker',
    targeting       = 'current_target',
    roundtime       = '3s',
    stamina         = '9',
    offensive_gear  = 'Right hand, arm accessory, or armor covering the arms',
    requirements    = 'An empty right hand (or holding a brawling weapon in it).  Training in Brawling is recommended.',
    description     = 'Attempt to daze your opponent with a roundhouse punch to the head.',
    mechanics       = 'Maneuver a target with a punch to the head.  Applies [[Confused]] to the target for {{mono|(5 + (Rank * 2))}} seconds and [[Staggered]] for {{mono|(Success Margin / 10)}} seconds.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "monk" },
}

Maneuvers['headbutt'] = def {
    mnemonic        = 'headbutt',
    name            = 'Headbutt',
    type            = 'setup',
    raw_type        = 'Setup',
    category        = 'general',
    raw_category    = '',
    family          = 'setup',
    handler_key     = 'headbutt',
    targeting       = 'current_target',
    roundtime       = '3s',
    stamina         = '9',
    offensive_gear  = 'Helmet, or armor covering the head',
    requirements    = '',
    description     = 'Slam your head into your opponent\'s head.',
    mechanics       = 'Maneuver a target, dealing minor [[crush critical table|crush]] damage with your head.  Helmets provide a bonus and are more effective than regular [[armor]].  Can force targets to [[kneel]], [[stun]] them, or render them [[unconscious]].  Applies [[Staggered]] for {{mono|(Success Margin / 10)}} seconds.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "rogue", "monk", "paladin" },
}

Maneuvers['iharmony'] = def {
    mnemonic        = 'iharmony',
    name            = 'Inner Harmony',
    type            = 'martial_stance',
    raw_type        = 'Martial Stance',
    category        = 'general',
    raw_category    = '',
    family          = 'stance',
    handler_key     = 'iharmony',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '20',
    offensive_gear  = '',
    requirements    = '',
    description     = 'You focus yourself in order to shake off many negative spell effects.',
    mechanics       = 'You have a 75% chance at rank 1, and a 100% chance at rank 2, to shake off a negative [[spell]] effect every 30 seconds.  At rank 3, you may shake off a negative spell effect immediately upon assuming the stance.  Every 5 ranks of [[Mental Lore, Telepathy|Telepathy]] lore reduces the time of the next removal by 1 sec.  This benefit caps out at 100 ranks for a 20 second reduction.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 3,
    rank_costs      = { 3, 6, 9, 0, 0 },
    available_to    = { "monk" },
}

Maneuvers['ipower'] = def {
    mnemonic        = 'ipower',
    name            = 'Internal Power',
    type            = 'buff',
    raw_type        = 'Buff',
    category        = 'general',
    raw_category    = '',
    family          = 'buff',
    handler_key     = 'ipower',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '20',
    offensive_gear  = '',
    requirements    = '',
    description     = 'Restore your inner well-being and heal yourself.',
    mechanics       = 'Allows you to immediately heal up to {{mono|(15 + (5 * rank))}} [[health|Health Points (HP)]] upon invocation.  At rank 5, if already at full HP, this maneuver can be used to heal a minor [[wound]].  This latter use requires 10 seconds of [[Roundtime]], which can be reduced by one second per three ranks of [[Mental Lore, Transformation|Mental Lore: Transformation]].',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "monk" },
}

Maneuvers['kifocus'] = def {
    mnemonic        = 'kifocus',
    name            = 'Ki Focus',
    type            = 'buff',
    raw_type        = 'Buff',
    category        = 'general',
    raw_category    = '',
    family          = 'buff',
    handler_key     = 'kifocus',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '20',
    offensive_gear  = '',
    requirements    = '',
    description     = 'Center yourself and focus on your inner ki to enhance your next unarmed strike.',
    mechanics       = 'You have a 33% per rank chance of achieving an immediate tier-up, or a significant chance of earning a tier-up strike on subsequent attacks when the immediate tier-up is not successful.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 3,
    rank_costs      = { 3, 6, 9, 0, 0 },
    available_to    = { "monk" },
}

Maneuvers['kickspec'] = def {
    mnemonic        = 'kickspec',
    name            = 'Kick Specialization',
    type            = 'passive',
    raw_type        = 'Passive',
    category        = 'general',
    raw_category    = '',
    family          = 'passive',
    handler_key     = 'kickspec',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '',
    offensive_gear  = '',
    requirements    = '',
    description     = 'You specialize in kicking during unarmed combat.',
    mechanics       = 'When using {{boldmono|[[KICK]]}}, you gain {{mono|(Rank * 2)}} to [[Multiplier modifier|Multiplier Modifier (MM)]] and an additional {{mono|(Rank * 2)%}} chance to present a tier-up opening.  Only one of [[Punch Specialization]], Kick Specialization, or [[Grapple Specialization]] may be trained.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "rogue", "monk" },
}

Maneuvers['kneebash'] = def {
    mnemonic        = 'kneebash',
    name            = 'Kneebash',
    type            = 'setup',
    raw_type        = 'Setup',
    category        = 'rogue_guild',
    raw_category    = 'Rogue Guild',
    family          = 'setup',
    handler_key     = 'kneebash',
    targeting       = 'current_target',
    roundtime       = '2s',
    stamina         = '7',
    offensive_gear  = 'Right hand',
    requirements    = '',
    description     = 'Thwap an opponent\'s kneecap to knock them to their knees.',
    mechanics       = 'Maneuver a target and force them to [[kneeling]].  Applies [[Crippled]] with a power of {{mono|(Success Margin / 4)}} for {{mono|(5 + (Success Margin / 6))}} seconds and [[Staggered]] for {{mono|(Success Margin / 6)}} seconds.',
    is_guild_skill  = true,
    is_learnable    = true,
    max_rank        = 1,
    rank_costs      = { 0, 0, 0, 0, 0 },
    available_to    = { "rogue", "bard", "monk" },
}

Maneuvers['leapattack'] = def {
    mnemonic        = 'leapattack',
    name            = 'Leap Attack',
    type            = 'attack',
    raw_type        = 'Attack',
    category        = 'general',
    raw_category    = '',
    family          = 'attack',
    handler_key     = 'leapattack',
    targeting       = 'current_target',
    roundtime       = 'ATTACK-2',
    stamina         = '15',
    offensive_gear  = 'Both hands',
    requirements    = '',
    description     = 'Leap into the air to attack a flying target.',
    mechanics       = 'Leap into the air to make an unaimed attack against a [[flying]] target.',
    hotbar_ready    = { kind = 'target_flag_any', flags = { 'flying', 'airborne', 'levitating', 'hovering' }, message = 'That maneuver requires a flying target.' },
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 1,
    rank_costs      = { 10, 0, 0, 0, 0 },
    available_to    = { "warrior", "rogue", "ranger", "monk" },
}

Maneuvers['mblow'] = def {
    mnemonic        = 'mblow',
    name            = 'Mighty Blow',
    type            = 'attack',
    raw_type        = 'Attack',
    category        = 'general',
    raw_category    = '',
    family          = 'attack',
    handler_key     = 'mblow',
    targeting       = 'current_target',
    roundtime       = 'ATTACK-1',
    stamina         = '15',
    offensive_gear  = 'Both hands',
    requirements    = 'Polearms cannot be used with this maneuver.',
    description     = 'Attempt to smash your opponent with a powerful swing.',
    mechanics       = 'Increases [[Damage Factor]] by {{mono|(Rank * 10)%}} and reduces target [[stance]] by {{mono|(Rank * 5)%}}.  These effects last for one swing only.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior" },
}

Maneuvers['mug'] = def {
    mnemonic        = 'mug',
    name            = 'Mug',
    type            = 'attack',
    raw_type        = 'Attack',
    category        = 'general',
    raw_category    = '',
    family          = 'attack',
    handler_key     = 'mug',
    targeting       = 'current_target',
    roundtime       = 'ATTACK-2',
    stamina         = '15',
    offensive_gear  = 'Both hands, gloves, or armor covering the hands',
    requirements    = '',
    description     = 'Plunder your target\'s pockets as you distract them with an attack.',
    mechanics       = 'Attack a target and simultaneously attempt to [[steal]] from them.  Stealing from creatures can produce treasure as if you {{boldmono|[[LOOT]]ed}} their corpse.  Stealing from a creature can only be done once per creature.  Success based on [[Pickpocketing]] skill, higher success if done from [[stealth|hiding]]. Please note that many creatures cannot be mugged due to their coding. In such cases, you will receive a message saying the creature is "too wary" - this is not a failure, the action simply is not possible (generally very old creatures cannot be mugged, such as those in the Broken Lands).',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "rogue" },
}

Maneuvers['nosetweak'] = def {
    mnemonic        = 'nosetweak',
    name            = 'Nosetweak',
    type            = 'setup',
    raw_type        = 'Setup',
    category        = 'rogue_guild',
    raw_category    = 'Rogue Guild',
    family          = 'setup',
    handler_key     = 'nosetweak',
    targeting       = 'current_target',
    roundtime       = '2s',
    stamina         = '7',
    offensive_gear  = 'Gloves, or armor covering the hands',
    requirements    = '',
    description     = 'Tweak an opponent\'s nose to distract them from attacking.',
    mechanics       = 'Maneuver a target to apply [[Demoralized]] with a power of 20 for {{mono|(5 + (Success Margin / 4))}} seconds.',
    is_guild_skill  = true,
    is_learnable    = true,
    max_rank        = 1,
    rank_costs      = { 0, 0, 0, 0, 0 },
    available_to    = { "rogue", "bard", "monk" },
}

Maneuvers['parryspec'] = def {
    mnemonic        = 'parryspec',
    name            = 'Parry Specialization',
    type            = 'passive',
    raw_type        = 'Passive',
    category        = 'general',
    raw_category    = '',
    family          = 'passive',
    handler_key     = 'parryspec',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '',
    offensive_gear  = '',
    requirements    = '',
    description     = 'You specialize in parrying attacks with a [[weapon]].',
    mechanics       = 'Increase your [[parry]] chance by 5% per rank.  You have a {{mono|(10 + (5 * Rank))%}} chance to gain [[Counter]] when parrying an attack in an aggressive [[stance]].  Only one of [[Block Specialization]], [[Evade Specialization]], or Parry Specialization may be trained.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 3,
    rank_costs      = { 4, 8, 12, 0, 0 },
    available_to    = { "warrior", "rogue", "monk" },
}

Maneuvers['precision'] = def {
    mnemonic        = 'precision',
    name            = 'Precision',
    type            = 'passive',
    raw_type        = 'Passive',
    category        = 'general',
    raw_category    = '',
    family          = 'passive',
    handler_key     = 'precision',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '',
    offensive_gear  = '',
    requirements    = '',
    description     = 'Wield your weapons with precision, applying only the type of damage you choose.',
    mechanics       = 'Precision allows you to specify the damage type of a weapon ([[crush]]ing, [[slash]]ing, or [[puncture]]) when used in combat.  Up to 30 weapon types can be specified, and your preference will be stored and automatic, can also be cleared or reset.  At one rank, your preference will be used 75% of the time, else the weapon has its normal damage chances.  At two ranks, the weapon will always deliver your preferred type of damage.  Precision does not function with aimed (ambush) or ranged attacks.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 2,
    rank_costs      = { 4, 6, 0, 0, 0 },
    available_to    = { "warrior", "rogue", "wizard", "cleric", "empath", "sorcerer", "ranger", "bard", "paladin", "monk" },
}

Maneuvers['predator'] = def {
    mnemonic        = 'predator',
    name            = 'Predator\'s Eye',
    type            = 'martial_stance',
    raw_type        = 'Martial Stance',
    category        = 'general',
    raw_category    = '',
    family          = 'stance',
    handler_key     = 'predator',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '20',
    offensive_gear  = '',
    requirements    = 'A melee [[weapon]] with Base Weapon Speed 3 or less.',
    description     = 'You have deadly aim when [[ambush]]ing with light weapons.',
    mechanics       = 'Your chance to hit the body part you [[aim]] for increases by 4% at rank 1, 7% at rank 2 and 10% at rank 3.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 3,
    rank_costs      = { 3, 6, 9, 0, 0 },
    available_to    = { "rogue" },
}

Maneuvers['punchspec'] = def {
    mnemonic        = 'punchspec',
    name            = 'Punch Specialization',
    type            = 'passive',
    raw_type        = 'Passive',
    category        = 'general',
    raw_category    = '',
    family          = 'passive',
    handler_key     = 'punchspec',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '',
    offensive_gear  = '',
    requirements    = '',
    description     = 'You specialize in punching during [[unarmed combat]].',
    mechanics       = 'When using {{boldmono|[[PUNCH]]}}, you gain {{mono|(Rank * 2)}} to [[Multiplier modifier|Multiplier Modifier (MM)]] and an additional {{mono|(Rank * 2)%}} chance to present a tier-up opening.  Only one of Punch Specialization, [[Kick Specialization]], or [[Grapple Specialization]] may be trained.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "rogue", "monk" },
}

Maneuvers['retreat'] = def {
    mnemonic        = 'retreat',
    name            = 'Retreat',
    type            = 'buff',
    raw_type        = 'Buff',
    category        = 'general',
    raw_category    = '',
    family          = 'buff',
    handler_key     = 'retreat',
    targeting       = 'none',
    roundtime       = '3s',
    stamina         = '10',
    offensive_gear  = '',
    requirements    = '',
    description     = 'Tactically retreat from close quarter combat.',
    mechanics       = 'Applies [[Disengaged]] for {{mono|(5 + (Rank * 2))}} seconds.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "rogue", "wizard", "cleric", "empath", "sorcerer", "ranger", "bard", "paladin", "monk" },
}

Maneuvers['krynch'] = def {
    mnemonic        = 'krynch',
    name            = 'Rolling Krynch Stance',
    type            = 'martial_stance',
    raw_type        = 'Martial Stance',
    category        = 'general',
    raw_category    = '',
    family          = 'stance',
    handler_key     = 'krynch',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '20',
    offensive_gear  = '',
    requirements    = 'Training in Multi-Opponent Combat is recommended.',
    description     = 'Use your positioning and momentum to turn your advantage against one foe to another.',
    mechanics       = 'You position yourself to apply the momentum from an [[Unarmed Combat System|unarmed attack]] against one foe, to your next unarmed attack against a different foe.  When at tier 3 on the first target, you have a {{mono|15/25/35%}} chance to maintain tier 3 against the second target, and a {{mono|30/40/50%}} chance to reach tier 2, at ranks 1/2/3.  At tier 2, you have a {{mono|45/55/65%}} chance to maintain tier 2 against the second target.  These chances are further modified by relative [[level]] and training in [[Multi Opponent Combat]].',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 3,
    rank_costs      = { 3, 6, 9, 0, 0 },
    available_to    = { "monk" },
}

Maneuvers['bash'] = def {
    mnemonic        = 'bash',
    name            = 'Shield Bash',
    type            = 'setup',
    raw_type        = 'Setup',
    category        = 'general',
    raw_category    = '',
    family          = 'setup',
    handler_key     = 'bash',
    targeting       = 'current_target',
    roundtime       = '3s',
    stamina         = '9',
    offensive_gear  = 'Left hand',
    requirements    = 'Requires a shield.',
    description     = 'Attempt to wallop your foe with your shield.',
    mechanics       = 'Maneuver a target with your [[shield]], dealing minor impact and minor unbalance damage.  Applies [[Vulnerable]] to the target for {{mono|(15 + (Rank * 5))}} seconds and [[Staggered]] for {{mono|(Success Margin / 5) seconds}}, and reduces stance.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "rogue", "paladin" },
}

Maneuvers['sidebyside'] = def {
    mnemonic        = 'sidebyside',
    name            = 'Side by Side',
    type            = 'passive',
    raw_type        = 'Passive',
    category        = 'general',
    raw_category    = '',
    family          = 'passive',
    handler_key     = 'sidebyside',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '',
    offensive_gear  = '',
    requirements    = '',
    description     = 'You and your allies are stronger together.',
    mechanics       = 'Side by Side gives a boost to melee [[Attack Strength]] and [[Defensive Strength]] when grouped with others with the Side By Side skill.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "rogue", "wizard", "cleric", "empath", "sorcerer", "ranger", "bard", "paladin", "monk" },
}

Maneuvers['slipperymind'] = def {
    mnemonic        = 'slipperymind',
    name            = 'Slippery Mind',
    type            = 'martial_stance',
    raw_type        = 'Martial Stance',
    category        = 'general',
    raw_category    = '',
    family          = 'stance',
    handler_key     = 'slipperymind',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '20',
    offensive_gear  = '',
    requirements    = '',
    description     = 'Blank your mind to avoid warding spells.',
    mechanics       = 'You have a chance based on your [[Armor|Armor Group]] to avoid [[warding]] spells.  Warding spells that you avoid while in an aggressive [[stance]] have a {{mono|(15 + (20 * Rank))%}} chance of being redirected to another target in the room or back to the caster.  If you fail to avoid a warding spell, you have a chance equivalent to your [[template:slipmindavoidance|avoidance %]] to add {{mono|(Level / 5)}} to Generic [[target defense|Target Defense (TD)]] for 15 seconds.  Avoidance chance is 9% in Cloth, 7% in Leather, 5% in Scale, 3% in Chain, and 1% in Plate per rank.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 3,
    rank_costs      = { 3, 6, 9, 0, 0 },
    available_to    = { "rogue", "monk" },
}

Maneuvers['scleave'] = def {
    mnemonic        = 'scleave',
    name            = 'Spell Cleave',
    type            = 'setup',
    raw_type        = 'Setup',
    category        = 'general',
    raw_category    = '',
    family          = 'setup',
    handler_key     = 'scleave',
    targeting       = 'current_target',
    roundtime       = '3s',
    stamina         = '9',
    offensive_gear  = 'Right hand',
    requirements    = 'An [[Ensorcell (735)|ensorcelled]] or anti-magical (veil iron/krodera/kroderine) weapon.',
    description     = 'Attempt to use the unnatural energy of your [[weapon]] to cleave away a [[spell]] from your target.',
    mechanics       = 'Attempt to cleave away up to one spell at ranks 1-4, and two spells at rank 5.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "monk", "paladin" },
}

Maneuvers['sparry'] = def {
    mnemonic        = 'sparry',
    name            = 'Spell Parry',
    type            = 'passive',
    raw_type        = 'Passive',
    category        = 'general',
    raw_category    = '',
    family          = 'passive',
    handler_key     = 'sparry',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '',
    offensive_gear  = '',
    requirements    = '',
    description     = 'Your training allows you to [[parry]] magical [[bolt]]s.',
    mechanics       = 'Allows the parrying of magical ball/bolt spells at 75% of your normal parry chance, provided that you are using an [[Ensorcell (735)|ensorcelled]] or anti-magical weapon to do so.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 1,
    rank_costs      = { 10, 0, 0, 0, 0 },
    available_to    = { "warrior", "rogue", "monk" },
}

Maneuvers['sthieve'] = def {
    mnemonic        = 'sthieve',
    name            = 'Spell Thieve',
    type            = 'setup',
    raw_type        = 'Setup',
    category        = 'general',
    raw_category    = '',
    family          = 'setup',
    handler_key     = 'sthieve',
    targeting       = 'current_target',
    roundtime       = '3s',
    stamina         = '9',
    offensive_gear  = 'Right hand',
    requirements    = 'An [[Ensorcell (735)|ensorcelled]] or anti-magical (veil iron/krodera/kroderine) weapon.',
    description     = 'Attempt to use the unnatural energy of your [[weapon]] to sever a spell away from your target.',
    mechanics       = 'Attempt to steal up to one [[spell]] from the target.  Any magic stolen this way cannot be dispelled by environmental effects and lasts for {{mono|(20 + (Rank * 20))}} seconds.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "rogue", "ranger", "bard" },
}

Maneuvers['spikefocus'] = def {
    mnemonic        = 'spikefocus',
    name            = 'Spike Focus',
    type            = 'passive',
    raw_type        = 'Passive',
    category        = 'general',
    raw_category    = '',
    family          = 'passive',
    handler_key     = 'spikefocus',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '',
    offensive_gear  = '',
    requirements    = '',
    description     = 'Spiked armor no longer hinders you.',
    mechanics       = 'Reduces the penalty when using [[spikes|spiked]] [[ armor]] or [[shield]]s in conjunction with a maneuver by -5 per rank.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 2,
    rank_costs      = { 4, 8, 0, 0, 0 },
    available_to    = { "warrior", "rogue", "ranger", "bard", "monk", "paladin" },
}

Maneuvers['sattack'] = def {
    mnemonic        = 'sattack',
    name            = 'Spin Attack',
    type            = 'attack',
    raw_type        = 'Attack',
    category        = 'warrior_guild',
    raw_category    = 'Warrior Guild',
    family          = 'attack',
    handler_key     = 'sattack',
    targeting       = 'current_target',
    roundtime       = 'ATTACK-2',
    stamina         = '15',
    offensive_gear  = 'Both hands',
    requirements    = '',
    description     = 'Make a flashy, spinning attack against your target.',
    mechanics       = 'Grants a bonus of {{mono|(Rank * 3)}} to [[attack strength|Attack Strength (AS)]] for the duration of one attack.  Applies [[Enhance (effect)|Enhance Dodge]] with a power of {{mono|(3 * Rank)}} for 10 seconds.',
    is_guild_skill  = true,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "rogue", "ranger", "bard", "monk", "paladin" },
}

Maneuvers['sblow'] = def {
    mnemonic        = 'sblow',
    name            = 'Staggering Blow',
    type            = 'attack',
    raw_type        = 'Attack',
    category        = 'general',
    raw_category    = '',
    family          = 'attack',
    handler_key     = 'sblow',
    targeting       = 'current_target',
    roundtime       = 'ATTACK-2',
    stamina         = '15',
    offensive_gear  = 'Both hands',
    requirements    = 'Cannot be used with small weapons or closed fist attacks. Cannot be used with two weapon combat.',
    description     = 'Swing at your opponent and attempt to knock them off balance.',
    mechanics       = 'Attack a target dealing weapon damage. Applies [[Staggered]] for ((Damage Inflicted / 20) + Rank) seconds. With 15 Strength Bonus or higher, the target may be knocked across the room taking moderate unbalance damage.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "paladin" },
}

Maneuvers['mongoose'] = def {
    mnemonic        = 'mongoose',
    name            = 'Stance of the Mongoose',
    type            = 'martial_stance',
    raw_type        = 'Martial Stance',
    category        = 'general',
    raw_category    = '',
    family          = 'stance',
    handler_key     = 'mongoose',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '20',
    offensive_gear  = '',
    requirements    = 'A weapon suitable for a retaliatory attack, or an empty hand.',
    description     = '',
    mechanics       = 'If you successfully [[parry]] an attack while in a forward or greater [[stance]], you will launch an automatic retaliatory strike at -2 RT.  The chance to make this strike is {{mono|50/75/100%}} at ranks 1/2/3, and such strikes are limited to one every {{mono|(6 - Rank)}} seconds.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 3,
    rank_costs      = { 3, 6, 9, 0, 0 },
    available_to    = { "warrior", "rogue", "monk" },
}

Maneuvers['stance'] = def {
    mnemonic        = 'stance',
    name            = 'Stance Perfection',
    type            = 'passive',
    raw_type        = 'Passive',
    category        = 'warrior_guild',
    raw_category    = 'Warrior Guild',
    family          = 'passive',
    handler_key     = 'stance',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '',
    offensive_gear  = '',
    requirements    = '',
    description     = 'Your training has improved your ability to refine your stance.',
    mechanics       = 'Rank 1 allows for further refinement of [[stance]] in intervals of 5.  Rank 2 allows you to specify the order of [[Evade]], [[Block]], and [[Parry]] in combat.  See {{boldmono|[[CMAN]] STANCE}} for more information.',
    is_guild_skill  = true,
    is_learnable    = true,
    max_rank        = 2,
    rank_costs      = { 4, 8, 0, 0, 0 },
    available_to    = { "warrior", "rogue", "wizard", "cleric", "empath", "sorcerer", "ranger", "bard", "paladin", "monk" },
}

Maneuvers['asp'] = def {
    mnemonic        = 'asp',
    name            = 'Striking Asp Stance',
    type            = 'martial_stance',
    raw_type        = 'Martial Stance',
    category        = 'general',
    raw_category    = '',
    family          = 'stance',
    handler_key     = 'asp',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '20',
    offensive_gear  = '',
    requirements    = '',
    description     = 'Strike quickly and with less effort.',
    mechanics       = 'Unless the cooldown is active, you will be able to automatically perform one single target {{boldmono|[[QUICKSTRIKE]]}} at a discounted [[stamina]] cost.  The stamina cost is reduced to 2/3, 1/2, and 1/3 at ranks 1, 2, and 3, respectively.  The cooldown lasts 60 seconds, and begins immediately when a discounted {{boldmono|QUICKSTRIKE}} is performed.  At rank 3, if 60 seconds pass without an active cooldown, up to 1 charge will be stored and automatically used if a {{boldmono|QUICKSTRIKE}} is performed during a cooldown.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 3,
    rank_costs      = { 3, 6, 9, 0, 0 },
    available_to    = { "warrior", "rogue", "monk" },
}

Maneuvers['stunman'] = def {
    mnemonic        = 'stunman',
    name            = 'Stun Maneuvers',
    type            = 'buff',
    raw_type        = 'Buff',
    category        = 'rogue_guild',
    raw_category    = 'Rogue Guild',
    family          = 'buff',
    handler_key     = 'stunman',
    targeting       = 'none',
    roundtime       = '3s',
    stamina         = '10',
    offensive_gear  = '',
    requirements    = 'Being stunned.',
    description     = 'Attempt to perform various actions while stunned.',
    mechanics       = ':Shield (Rank 1)  - Attempt to ready a [[shield]] in your left hand.',
    is_guild_skill  = true,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "rogue", "monk" },
}

Maneuvers['subdue'] = def {
    mnemonic        = 'subdue',
    name            = 'Subdue',
    type            = 'setup',
    raw_type        = 'Setup',
    category        = 'rogue_guild',
    raw_category    = 'Rogue Guild',
    family          = 'setup',
    handler_key     = 'subdue',
    targeting       = 'current_target',
    roundtime       = '3s',
    stamina         = '9',
    offensive_gear  = 'Right hand',
    requirements    = '',
    description     = 'Spring from hiding and attempt to disable your foe.',
    mechanics       = 'Maneuver a target and attempt to knockdown, [[stun]], or [[immobilized|immobilize]] them.  Can also reduce [[stance]].',
    is_guild_skill  = true,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "rogue" },
}

Maneuvers['spunch'] = def {
    mnemonic        = 'spunch',
    name            = 'Sucker Punch',
    type            = 'setup',
    raw_type        = 'Setup',
    category        = 'general',
    raw_category    = '',
    family          = 'setup',
    handler_key     = 'spunch',
    targeting       = 'current_target',
    roundtime       = '2s',
    stamina         = '7',
    offensive_gear  = 'Right hand, gloves, or armor covering the hands',
    requirements    = '',
    description     = 'A quick punch to the target\'s kidneys.',
    mechanics       = 'Maneuver a target to [[stun]], do damage, and cause a drop in [[stance]].  Applies [[Silenced]] for {{mono|(Rank * 2)}} seconds and [[Staggered]] for {{mono|(Success Margin / 8)}} seconds.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "rogue", "monk" },
}

Maneuvers['sunder'] = def {
    mnemonic        = 'sunder',
    name            = 'Sunder Shield',
    type            = 'setup',
    raw_type        = 'Setup',
    category        = 'general',
    raw_category    = '',
    family          = 'setup',
    handler_key     = 'sunder',
    targeting       = 'current_target',
    roundtime       = '2s',
    stamina         = '7',
    offensive_gear  = 'Right hand',
    requirements    = 'A [[weapon]] capable of sundering a shield (not a rapier, whip, dagger, polearm or brawling weapon).',
    description     = 'Attempt to break or disarm a target\'s shield.',
    mechanics       = 'Maneuver a target and break or [[disarm]] their [[shield]].  Magical shields resist sundering, but cause their holder to temporarily lose their ability to [[block]].  Applies [[Staggered]] for {{mono|(Success Margin / 5)}} seconds.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "paladin" },
}

Maneuvers['surge'] = def {
    mnemonic        = 'surge',
    name            = 'Surge of Strength',
    type            = 'buff',
    raw_type        = 'Buff',
    category        = 'general',
    raw_category    = '',
    family          = 'buff',
    handler_key     = 'surge',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '30.  There is a recovery period during which the reactivation cost doubles.',
    offensive_gear  = '',
    requirements    = '',
    description     = 'Dig deep for a Burst of Strength.',
    mechanics       = 'Apply [[Enhance (effect)|Enhance Strength]] with a power of {{mono|(12 + (4 * Rank))}} for 90 seconds (refreshable).',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "rogue", "monk", "paladin" },
}

Maneuvers['sweep'] = def {
    mnemonic        = 'sweep',
    name            = 'Sweep',
    type            = 'setup',
    raw_type        = 'Setup',
    category        = 'rogue_guild',
    raw_category    = 'Rogue Guild',
    family          = 'setup',
    handler_key     = 'sweep',
    targeting       = 'current_target',
    roundtime       = '2s',
    stamina         = '7',
    offensive_gear  = 'Leg accessory, or armor covering the legs',
    requirements    = '',
    description     = 'Attempt to knock a foe to the ground by sweeping their legs out from under them.',
    mechanics       = 'Maneuver a target to knock them [[prone]].  Applies [[Vulnerable]] for {{mono|(15 + (Rank * 5))}} seconds, and [[Staggered]] for {{mono|(Success Margin / 6)}} seconds.',
    is_guild_skill  = true,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "rogue", "ranger", "bard", "monk" },
}

Maneuvers['swiftkick'] = def {
    mnemonic        = 'swiftkick',
    name            = 'Swiftkick',
    type            = 'setup',
    raw_type        = 'Setup',
    category        = 'rogue_guild',
    raw_category    = 'Rogue Guild',
    family          = 'setup',
    handler_key     = 'swiftkick',
    targeting       = 'current_target',
    roundtime       = '2s',
    stamina         = '7',
    offensive_gear  = 'Leg accessory, or armor covering the legs',
    requirements    = '',
    description     = 'Embarrass your opponent into a blind rage.',
    mechanics       = 'Maneuver a target to force them to offensive [[stance]].  Applies [[Staggered]] for {{mono|(Success Margin / 10)}} seconds.',
    is_guild_skill  = true,
    is_learnable    = true,
    max_rank        = 1,
    rank_costs      = { 0, 0, 0, 0, 0 },
    available_to    = { "rogue", "bard", "monk" },
}

Maneuvers['tackle'] = def {
    mnemonic        = 'tackle',
    name            = 'Tackle',
    type            = 'setup',
    raw_type        = 'Setup',
    category        = 'warrior_guild',
    raw_category    = 'Warrior Guild',
    family          = 'setup',
    handler_key     = 'tackle',
    targeting       = 'current_target',
    roundtime       = '2s',
    stamina         = '7',
    offensive_gear  = 'Arm accessory, or [[armor]] covering the arms',
    requirements    = '',
    description     = 'Hurl yourself at a target and attempt to knock them down.',
    mechanics       = 'Maneuver a target to bring them to the ground.  Applies [[Vulnerable]] for {{mono|(15 + (Rank * 5))}} seconds and [[Staggered]] for {{mono|(3 + (Success Margin / 6))}} seconds.',
    is_guild_skill  = true,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior" },
}

Maneuvers['tainted'] = def {
    mnemonic        = 'tainted',
    name            = 'Tainted Bond',
    type            = 'passive',
    raw_type        = 'Passive',
    category        = 'general',
    raw_category    = '',
    family          = 'passive',
    handler_key     = 'tainted',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '',
    offensive_gear  = '',
    requirements    = 'A weapon fully bonded to you through either the [[Weapon Bonding]] combat maneuver or the [[Holy Weapon (1625)|Holy Weapon]] spell.',
    description     = 'The energizing effect of the necrotic energy suffusing your bonded [[weapon]] lingers for a second attack.',
    mechanics       = 'If you are using a permanently [[Ensorcell (735)|ensorcelled]] and fully bonded weapon in combat, you will gain one extra attack before expending the periodic attack boost from the ensorcelled necrotic infusions.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 1,
    rank_costs      = { 20, 0, 0, 0, 0 },
    available_to    = { "warrior", "paladin" },
}

Maneuvers['templeshot'] = def {
    mnemonic        = 'templeshot',
    name            = 'Templeshot',
    type            = 'setup',
    raw_type        = 'Setup',
    category        = 'rogue_guild',
    raw_category    = 'Rogue Guild',
    family          = 'setup',
    handler_key     = 'templeshot',
    targeting       = 'current_target',
    roundtime       = '2s',
    stamina         = '7',
    offensive_gear  = 'Right hand',
    requirements    = '',
    description     = 'Smack an opponent in the head to increase their reaction time.',
    mechanics       = 'Maneuver a target to apply [[Dazed]] with a power of {{mono|(Rank - 2)}} for {{mono|(5 + (Success Margin / 6))}} seconds.',
    is_guild_skill  = true,
    is_learnable    = true,
    max_rank        = 1,
    rank_costs      = { 0, 0, 0, 0, 0 },
    available_to    = { "rogue", "bard", "monk" },
}

Maneuvers['throatchop'] = def {
    mnemonic        = 'throatchop',
    name            = 'Throatchop',
    type            = 'setup',
    raw_type        = 'Setup',
    category        = 'rogue_guild',
    raw_category    = 'Rogue Guild',
    family          = 'setup',
    handler_key     = 'throatchop',
    targeting       = 'current_target',
    roundtime       = '2s',
    stamina         = '7',
    offensive_gear  = 'Right hand',
    requirements    = '',
    description     = 'Attempt to temporarily silence your opponent.',
    mechanics       = 'Maneuver a target to apply [[Silenced]] for {{mono|(5 + (Success Margin / 10))}} seconds.',
    is_guild_skill  = true,
    is_learnable    = true,
    max_rank        = 1,
    rank_costs      = { 0, 0, 0, 0, 0 },
    available_to    = { "rogue", "bard", "monk" },
}

Maneuvers['trip'] = def {
    mnemonic        = 'trip',
    name            = 'Trip',
    type            = 'setup',
    raw_type        = 'Setup',
    category        = 'general',
    raw_category    = '',
    family          = 'setup',
    handler_key     = 'trip',
    targeting       = 'current_target',
    roundtime       = '2s',
    stamina         = '7',
    offensive_gear  = 'Right hand',
    requirements    = 'A two-handed polearm or staff with at least 15 ranks in the relevant skill.  Training in Polearms (for polearms) or Two-Handed Weapons (for staves) is recommended.',
    description     = 'Attempt to trip your opponent with a [[polearm]] or [[staff]].  When using certain polearms, it must be [[Verb:GRIP|gripped]] with both hands, otherwise you can\'t reach far enough to trip anything holding it with one hand.',
    mechanics       = 'Maneuver a target, dealing moderate [[unbalance critical table|unbalance]] damage to the legs.  Applies [[Vulnerable]] for {{mono|(15 + (Rank * 5))}} seconds and [[Staggered]] for {{mono|(Success Margin / 7)}} seconds.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "rogue", "wizard", "cleric", "empath", "sorcerer", "ranger", "bard", "paladin", "monk" },
}

Maneuvers['truestrike'] = def {
    mnemonic        = 'truestrike',
    name            = 'True Strike',
    type            = 'attack',
    raw_type        = 'Attack',
    category        = 'general',
    raw_category    = '',
    family          = 'attack',
    handler_key     = 'truestrike',
    targeting       = 'current_target',
    roundtime       = 'ATTACK-1',
    stamina         = '15',
    offensive_gear  = 'Both hands',
    requirements    = '',
    description     = 'Attack a target with a true strike.',
    mechanics       = 'Increases the chance to hit your target for one attack.  At Rank 1, True Strike changes the standard attack d100 roll to {{mono|20 + d80}} and reduces the target\'s chances of evading, parrying, and/or blocking your attack by 10%.  Each additional rank adds 10 to your combat roll {{mono|(d80, d70, d60, d50, d40)}} and reduces your opponent\'s evasion, parry, and blocking ability by a further 10%.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "rogue", "ranger", "bard", "monk", "paladin" },
}

Maneuvers['unarmedspec'] = def {
    mnemonic        = 'unarmedspec',
    name            = 'Unarmed Specialist',
    type            = 'passive',
    raw_type        = 'Passive',
    category        = 'general',
    raw_category    = '',
    family          = 'passive',
    handler_key     = 'unarmedspec',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '',
    offensive_gear  = '',
    requirements    = '',
    description     = 'Your hands are your weapons; you can perform certain [[maneuver]]s bare-handed.',
    mechanics       = 'This maneuver will grant the ability to use some maneuvers without requiring a melee [[weapon]]. Specifically [[Cheapshots]]: [[Templeshot]], [[Kneebash]] & [[Throatchop]], [[Disarm]], [[Feint]], and [[Subdue]]. [[Monk]]s are already considered Unarmed Specialists. It is important to know that rank 5 masters of a skill can already do that skill bare-handed.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 1,
    rank_costs      = { 6, 0, 0, 0, 0 },
    available_to    = { "warrior", "rogue", "wizard", "cleric", "empath", "sorcerer", "ranger", "bard", "paladin" },
}

Maneuvers['vaultkick'] = def {
    mnemonic        = 'vaultkick',
    name            = 'Vault Kick',
    type            = 'setup',
    raw_type        = 'Setup',
    category        = 'general',
    raw_category    = '',
    family          = 'setup',
    handler_key     = 'vaultkick',
    targeting       = 'current_target',
    roundtime       = '3s',
    stamina         = '9',
    offensive_gear  = 'Right hand, boots, or armor covering the feet',
    requirements    = '',
    description     = 'Use your [[polearm]] or [[quarterstaff]] to vault forward and kick an opponent.',
    mechanics       = 'Maneuver a target, dealing minor [[impact critical table|impact]] and moderate [[unbalance critical table|unbalance]] damage.  Applies [[Dazed]] and [[Slowed]] to the target for {{mono|(15 + (Rank * 5))}} seconds.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "rogue", "ranger", "bard", "monk", "paladin" },
}

Maneuvers['wspec'] = def {
    mnemonic        = 'wspec',
    name            = 'Weapon Specialization',
    type            = 'passive',
    raw_type        = 'Passive',
    category        = 'general',
    raw_category    = '',
    family          = 'passive',
    handler_key     = 'wspec',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '',
    offensive_gear  = '',
    requirements    = 'A weapon type to specialize in.',
    description     = 'You have specialized in a weapon type through extensive training.',
    mechanics       = 'Adds +2 to [[attack strength|Attack Strength (AS)]] and bonuses to [[Player System Manager|PSM]] attack/defensive strength per rank when using a weapon of the type chosen to specialize in.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 5,
    rank_costs      = { 2, 4, 6, 8, 10 },
    available_to    = { "warrior", "rogue", "paladin" },
}

Maneuvers['dervish'] = def {
    mnemonic        = 'dervish',
    name            = 'Whirling Dervish',
    type            = 'martial_stance',
    raw_type        = 'Martial Stance',
    category        = 'general',
    raw_category    = '',
    family          = 'stance',
    handler_key     = 'dervish',
    targeting       = 'none',
    roundtime       = '',
    stamina         = '20',
    offensive_gear  = '',
    requirements    = '',
    description     = 'Switch between targets with relative ease when making multiple melee attacks.',
    mechanics       = 'You gain the ability to switch with relative ease between targets when making multiple melee attacks.  When making a focused {{boldmono|[[MSTRIKE]]}} or a two-weapon attack that slays your targeted creature foe, you have a chance to switch your remaining attacks to another foe in the room.  This chance is 5% + 25% per rank.',
    is_guild_skill  = false,
    is_learnable    = true,
    max_rank        = 3,
    rank_costs      = { 3, 6, 9, 0, 0 },
    available_to    = { "warrior", "rogue" },
}

Maneuvers._display_order = {
    'acrobatsleap',
    'bearhug',
    'berserk',
    'blockspec',
    'bullrush',
    'burst',
    'cheapshots',
    'focus',
    'mobility',
    'cmovement',
    'toughness',
    'coupdegrace',
    'cpress',
    'cdefense',
    'cutthroat',
    'dirtkick',
    'disarm',
    'dislodge',
    'divert',
    'duckandweave',
    'shroud',
    'evadespec',
    'eviscerate',
    'executioner',
    'exsanguinate',
    'eyepoke',
    'feint',
    'flurry',
    'footstomp',
    'garrote',
    'grapplespec',
    'griffin',
    'gkick',
    'hamstring',
    'haymaker',
    'headbutt',
    'iharmony',
    'ipower',
    'kifocus',
    'kickspec',
    'kneebash',
    'leapattack',
    'mblow',
    'mug',
    'nosetweak',
    'parryspec',
    'precision',
    'predator',
    'punchspec',
    'retreat',
    'krynch',
    'bash',
    'sidebyside',
    'slipperymind',
    'scleave',
    'sparry',
    'sthieve',
    'spikefocus',
    'sattack',
    'sblow',
    'mongoose',
    'stance',
    'asp',
    'stunman',
    'subdue',
    'spunch',
    'sunder',
    'surge',
    'sweep',
    'swiftkick',
    'tackle',
    'tainted',
    'templeshot',
    'throatchop',
    'trip',
    'truestrike',
    'unarmedspec',
    'vaultkick',
    'wspec',
    'dervish',
}

Maneuvers._by_type = {}
Maneuvers._by_category = {}
for mnemonic, meta in pairs(Maneuvers) do
    if type(meta) == "table" and mnemonic:sub(1, 1) ~= "_" then
        local typ = meta.type or "passive"
        local cat = meta.category or "general"
        Maneuvers._by_type[typ] = Maneuvers._by_type[typ] or {}
        table.insert(Maneuvers._by_type[typ], mnemonic)
        Maneuvers._by_category[cat] = Maneuvers._by_category[cat] or {}
        table.insert(Maneuvers._by_category[cat], mnemonic)
    end
end

local function _sort_bucket(bucket)
    table.sort(bucket, function(a, b)
        local an = (Maneuvers[a] and Maneuvers[a].name) or a
        local bn = (Maneuvers[b] and Maneuvers[b].name) or b
        return an < bn
    end)
end

for _, bucket in pairs(Maneuvers._by_type) do _sort_bucket(bucket) end
for _, bucket in pairs(Maneuvers._by_category) do _sort_bucket(bucket) end

function Maneuvers.can_use(mnemonic, profession_name)
    local meta = Maneuvers[mnemonic]
    if not meta then return false end
    local allowed = meta.available_to or ALL_PROFESSIONS
    local prof = tostring(profession_name or ""):lower()
    if prof == "" then return false end
    for _, value in ipairs(allowed) do
        if tostring(value):lower() == prof then
            return true
        end
    end
    return false
end

return Maneuvers
