-- 047_add_fake_players.sql
-- Run:
--   mysql --protocol=TCP --skip-ssl -u root gemstone_dev < database/migrations/047_add_fake_players.sql

CREATE TABLE IF NOT EXISTS synthetic_players_state (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    character_id BIGINT NOT NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    character_name VARCHAR(80) NOT NULL,
    race_id INT NOT NULL DEFAULT 1,
    race_name VARCHAR(64) NOT NULL DEFAULT 'Human',
    profession_id INT NOT NULL DEFAULT 1,
    profession_name VARCHAR(64) NOT NULL DEFAULT 'Warrior',
    gender VARCHAR(16) NOT NULL DEFAULT 'male',
    age INT NOT NULL DEFAULT 25,
    level INT NOT NULL DEFAULT 1,
    level_target INT NOT NULL DEFAULT 1,
    mbti VARCHAR(8) NOT NULL DEFAULT 'ISTJ',
    archetype VARCHAR(64) NOT NULL DEFAULT 'town_regular',
    home_region_key VARCHAR(64) NOT NULL DEFAULT '',
    home_room_id INT NOT NULL DEFAULT 0,
    current_room_id INT NOT NULL DEFAULT 0,
    health_current INT NOT NULL DEFAULT 1,
    health_max INT NOT NULL DEFAULT 1,
    mana_current INT NOT NULL DEFAULT 0,
    mana_max INT NOT NULL DEFAULT 0,
    spirit_current INT NOT NULL DEFAULT 10,
    spirit_max INT NOT NULL DEFAULT 10,
    stamina_current INT NOT NULL DEFAULT 1,
    stamina_max INT NOT NULL DEFAULT 1,
    silver INT NOT NULL DEFAULT 0,
    experience BIGINT NOT NULL DEFAULT 0,
    field_experience BIGINT NOT NULL DEFAULT 0,
    position VARCHAR(24) NOT NULL DEFAULT 'standing',
    stance VARCHAR(24) NOT NULL DEFAULT 'neutral',
    hidden TINYINT(1) NOT NULL DEFAULT 0,
    sneaking TINYINT(1) NOT NULL DEFAULT 0,
    in_combat TINYINT(1) NOT NULL DEFAULT 0,
    is_dead TINYINT(1) NOT NULL DEFAULT 0,
    death_room_id INT NOT NULL DEFAULT 0,
    death_stat_mult DECIMAL(6,3) NOT NULL DEFAULT 1.000,
    roundtime_end DOUBLE NOT NULL DEFAULT 0,
    stat_strength INT NOT NULL DEFAULT 70,
    stat_constitution INT NOT NULL DEFAULT 70,
    stat_dexterity INT NOT NULL DEFAULT 70,
    stat_agility INT NOT NULL DEFAULT 70,
    stat_discipline INT NOT NULL DEFAULT 70,
    stat_aura INT NOT NULL DEFAULT 70,
    stat_logic INT NOT NULL DEFAULT 70,
    stat_intuition INT NOT NULL DEFAULT 70,
    stat_wisdom INT NOT NULL DEFAULT 70,
    stat_influence INT NOT NULL DEFAULT 70,
    inventory_json LONGTEXT NULL,
    right_hand_json LONGTEXT NULL,
    left_hand_json LONGTEXT NULL,
    skills_json LONGTEXT NULL,
    injuries_json LONGTEXT NULL,
    status_effects_json LONGTEXT NULL,
    wounds_json LONGTEXT NULL,
    state_json LONGTEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_synthetic_players_character_id (character_id),
    UNIQUE KEY uq_synthetic_players_name (character_name),
    KEY idx_synthetic_players_active_room (active, current_room_id),
    KEY idx_synthetic_players_region (home_region_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS synthetic_player_memory (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    synthetic_player_id BIGINT UNSIGNED NOT NULL,
    player_character_id INT NOT NULL,
    affinity INT NOT NULL DEFAULT 0,
    interaction_count INT NOT NULL DEFAULT 0,
    last_topic VARCHAR(64) NOT NULL DEFAULT '',
    memory_json LONGTEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_synthetic_memory_pair (synthetic_player_id, player_character_id),
    KEY idx_synthetic_memory_player (player_character_id),
    CONSTRAINT fk_synthetic_memory_actor
        FOREIGN KEY (synthetic_player_id)
        REFERENCES synthetic_players_state(id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
