INSERT INTO items (
    id, name, short_name, noun, article, item_type, is_template,
    is_stackable, weight, value, container_capacity, container_type, worn_location,
    material, color, description, examine_text, lore_text, base_name, display_order
) VALUES
(
    7400,
    'a floating disk',
    'floating disk',
    'disk',
    'a',
    'container',
    1,
    0,
    0,
    0,
    8,
    'spell_summon',
    'floating_disk',
    'force',
    'shimmering',
    'A circular platform of translucent force hangs patiently in the air, waiting to bear whatever burdens are set upon it.',
    'The disk is not truly solid, but the force holding it together is steady enough to cradle gear without complaint.',
    'Conjured through Major Elemental magic, a floating disk will linger only so long as its spell does.',
    'floating disk',
    190
),
(
    7401,
    'a spirit servant',
    'spirit servant',
    'servant',
    'a',
    'container',
    1,
    0,
    0,
    0,
    2,
    'spell_summon',
    'spirit_servant',
    'spirit',
    'translucent',
    'A quiet servant-spirit hovers here, its ghostly hands poised to fetch, carry, and obey simple commands.',
    'The servant''s outline ripples like fog in moonlight.  It has just enough substance to clutch and carry objects for its summoner.',
    'Called from the Major Spiritual circle, a spirit servant is bound to simple labor and short errands.',
    'spirit servant',
    191
)
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    short_name = VALUES(short_name),
    noun = VALUES(noun),
    article = VALUES(article),
    item_type = VALUES(item_type),
    is_template = VALUES(is_template),
    is_stackable = VALUES(is_stackable),
    weight = VALUES(weight),
    value = VALUES(value),
    container_capacity = VALUES(container_capacity),
    container_type = VALUES(container_type),
    worn_location = VALUES(worn_location),
    material = VALUES(material),
    color = VALUES(color),
    description = VALUES(description),
    examine_text = VALUES(examine_text),
    lore_text = VALUES(lore_text),
    base_name = VALUES(base_name),
    display_order = VALUES(display_order);
